### ISSUE TITLE
Missing node-sass ??

### ISSUE THREAD

**Issue by MichaelMatejko** [silevis/reactgrid#10]
1. created new react app.
2. followed description from README
=>
Failed to compile
./node_modules/@silevis/reactgrid/lib/assets/core.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./node_modules/@silevis/reactgrid/lib/assets/core.scss)
To import Sass files, you first need to install node-sass.
Run `npm install node-sass` or `yarn add node-sass` inside your workspace.
Require stack:

**Comment by patryk0493** [comment]
Changed in [v.3.0.22](https://github.com/silevis/reactgrid/releases/tag/3.0.22)
