### ISSUE TITLE
[Request] Source code of /examples

### ISSUE THREAD

**Issue by hunterwilhelm** [silevis/reactgrid#100]
I was on https://reactgrid.com/examples/?example=customization and I don't see the source code for these examples.

Where can I find the source code for the above examples?

**Comment by AK-101111** [comment]
> Where can I find the source code for the above examples?

Would the examples from the website repo work for you? 

[reactgrid-website](https://github.com/silevis/reactgrid-website/tree/gh-pages-dev/src/samples/samplesSrc)

**Comment by hunterwilhelm** [comment]
Yes that works great 👍
