### ISSUE TITLE
Is there any pricing for this library ?

### ISSUE THREAD

**Issue by DVGY** [silevis/reactgrid#101]
**Describe the bug**

**Current behavior**
A clear and concise description of what you current see.

**Expected behavior**

**Screenshots or gifs**

**Your environment details**
 - Device:  [e.g. mobile/desktop]

**Comment by hunterwilhelm** [comment]
It is provided free of charge. From the license:

ReactGrid is published under the MIT License (MIT).

(c) 2022 Silevis Software Sp. z o.o.

Permission is hereby granted, **free of charge**, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

...
