### ISSUE TITLE
Is there any way to put image in a cell ?

### ISSUE THREAD

**Issue by DVGY** [silevis/reactgrid#102]
Is there any way to put an image in a cell?

**Comment by hunterwilhelm** [comment]
Yes, there is a guide in the docs on how to do this but the example is broken:
https://reactgrid.com/docs/4.0/5-create-your-own-cell-template/

Here is a working example of images in Custom Cell Templates.
https://codesandbox.io/s/reactgrid-cell-template-w-images-component-z8g1zj?file=/src/index.tsx
