### ISSUE TITLE
[Feature Request] Column icons (i.e. for sorting icons)

### ISSUE THREAD

**Issue by hunterwilhelm** [silevis/reactgrid#103]
I would like to handle column clicking events so I can allow the user to sort the data in the column similar to filters in excel or google sheets. 

How to implement:
* Expose a click handler on the columns 
* Allow a new property for icons to be placed on the right-hand side of the column header.

Is this possible?

**Comment by hunterwilhelm** [comment]
The example: https://reactgrid.com/examples/?example=budget-planner has some of the features that would be useful here. But I have no idea how you did it. Resolving #100 would also resolve this issue.

**Comment by czerwiukk** [comment]
As mentioned in #100, the source code for examples is here: [reactgrid-website](https://github.com/silevis/reactgrid-website/tree/gh-pages-dev/src/samples/samplesSrc).
