### ISSUE TITLE
It's possible use column FILTER and DATA ORDER column?

### ISSUE THREAD

**Issue by APMU** [silevis/reactgrid#105]
Hello,

ReactGrid is a nice project!

But, it's possible use/add column FILTER and DATA ORDER column features?

**Comment by czerwiukk** [comment]
Hello! ReactGrid is not a data table component. Its job is to just map your data into a spreadsheet. Of course, you can implement those features by yourself. If you're looking for such features out of the box, use AG Grid or Handsontable.
