### ISSUE TITLE
Query: How to load external CSV files and get the headers automatically?

### ISSUE THREAD

**Issue by getkub** [silevis/reactgrid#108]
**Describe the bug**
Examples provided have data embedded within the src/tsx file. Looking for an example
- to load external file
- to load the headers of the CSV file dynamically

**Current behavior**
Current examples have sample data embedded within the source code as example
```
const getPeople = (): Person[] => [
  { name: "Thomas", surname: "Goldman" },
  { name: "Susie", surname: "Quattro" },
  { name: "", surname: "" }
];
```

**Expected behavior**
Example to load external csv file something like below and get header rows automatically
```
const getPeople = (): Person[] => [
 load("../src/sample.csv")
];

const getColumns = (): Column[] => [
load ("row1", header_columns)
];
```

**Comment by czerwiukk** [comment]
Docs provide trivial examples for the sake of simplicity. Data can be loaded from every possible source then mapped to match the interface of ReactGrid. [Here's a simple example how to load CSV files using the `fs` module.](url)

**Comment by getkub** [comment]
> Docs provide trivial examples for the sake of simplicity. Data can be loaded from every possible source then mapped to match the interface of ReactGrid. [Here's a simple example how to load CSV files using the `fs` module.](url)

thanks. Unfortunately the Link is not working
