### ISSUE TITLE
Could not implement sorting on reorderable columns

### ISSUE THREAD

**Issue by cretupaul** [silevis/reactgrid#112]
**Describe the bug**
I have created a custom cell template and inside of the actual template I do have 2 buttons. The problem I am facing is for the reorderable columns, when I click on those buttons the 'onClick' event is fired just once, the first time. If I do press multiple times on the buttons, nothing happens. If I press on the other column buttons and coming back on the first column, the 'onclick' event fires for the first time and that's it.

**Expected behavior**
The 'onClick' event should fire each time I press the button.

**Comment by DLowHP** [comment]
Hi! I investigated this issue and found out that the click event doesn't go through the column selection overlay. I have recreated a basic cell template similar to what you've described and my current workaround is setting `zIndex` on the buttons. Take a look at [this sandbox](https://codesandbox.io/s/reactgrid-getting-started-forked-cnylcd).

**Comment by DLowHP** [comment]
I'm closing it because of lack of activity. If you need further help reopen this issue or create new.
