### ISSUE TITLE
On React 18.2, when doubleclicking on cell to edit, causes "t is undefined" error

### ISSUE THREAD

**Issue by edzehoo** [silevis/reactgrid#114]
**Environment : ReactJS 18.2/Typescript
ReactGrid Version : 4.0**

Tried following the basic code here at  https://reactgrid.com/docs/4.0/1-getting-started/ . We managed to get the grid to display, but when we tried to edit any cell (double click any cell), we would get a "t is undefined" error.

Full detailed error:
Ml@http://localhost:3000/main.9fd1c32d1ba239874528.hot-update.js:9469:11 updateReducer@http://localhost:3000/static/js/bundle.js:34121:26 useReducer@http://localhost:3000/static/js/bundle.js:35332:20 useReducer@http://localhost:3000/static/js/bundle.js:50731:25 Al@http://localhost:3000/main.9fd1c32d1ba239874528.hot-update.js:9493:46 renderWithHooks@http://localhost:3000/static/js/bundle.js:33770:31 updateFunctionComponent@http://localhost:3000/static/js/bundle.js:36970:24 beginWork@http://localhost:3000/static/js/bundle.js:38917:20 beginWork$1@http://localhost:3000/static/js/bundle.js:44665:18 performUnitOfWork@http://localhost:3000/static/js/bundle.js:43823:16 workLoopSync@http://localhost:3000/static/js/bundle.js:43736:26 renderRootSync@http://localhost:3000/static/js/bundle.js:43705:11 recoverFromConcurrentError@http://localhost:3000/static/js/bundle.js:43113:38 performConcurrentWorkOnRoot@http://localhost:3000/static/js/bundle.js:43014:26 workLoop@http://localhost:3000/static/js/bundle.js:52132:46 flushWork@http://localhost:3000/static/js/bundle.js:52106:18 performWorkUntilDeadline@http://localhost:3000/static/js/bundle.js:52390:25 Al@http://localhost:3000/main.9fd1c32d1ba239874528.hot-update.js:9489:11 div div n@http://localhost:3000/main.9fd1c32d1ba239874528.hot-update.js:9602:29 Dl@http://localhost:3000/main.9fd1c32d1ba239874528.hot-update.js:9626:11 ya@http://localhost:3000/main.9fd1c32d1ba239874528.hot-update.js:7898:11 n@http://localhost:3000/main.9fd1c32d1ba239874528.hot-update.js:8454:29 App@http://localhost:3000/main.91a117094e631e45461a.hot-update.js:74:66

Not sure if this is due to ReactJS 18.2 version?  We were only able to install Reactgrid on 18.2 by running it with the --legacy-peers-deps flag.

**Comment by czerwiukk** [comment]
Hello, please disable the strict mode, from React 18 up it breaks the component.
