### ISSUE TITLE
Catch lowercase alphabet character key code

### ISSUE THREAD

**Issue by sittaendah** [silevis/reactgrid#115]
### Case:
I am using a custom CellTemplate where I put some modifications on `handleKeyDown`. I want to take general inputs (like alphanumeric, symbols), basically characters we usually type on an Excel/gsheet cell.

I notice that ReactGrid always take the capital form for each letter I type when I am on an active selected cell (just right before it goes to edit mode). Ex: for both `A` and `a`, I got `65` on `handleKeyDown`. I checked on `keyCodes.ts` on the lib repo, there only listed the ASCII codes for capital letters.

### Expectation:
Able to differentiate uppercase and lowercase alphabet characters on `handleKeyDown`

**Note**
I'd like to recommend adding additional key codes on the constants. Also welcome for any workaround I can try in the meantime :)

**Comment by DLowHP** [comment]
You can use `getCharFromKeyCode(keyCode, shift)` to retrieve desired alphanumeric characters 😉
