### ISSUE TITLE
Part of rows hidden

### ISSUE THREAD

**Issue by othman-19** [silevis/reactgrid#116]
A part of rows is hidden, it only appears when I click on the cell position.

https://user-images.githubusercontent.com/42877188/179425290-f89ddee2-5869-4204-b84f-6d7da2f3e76a.mov

**Comment by robertgutu** [comment]
I have the same issue with a grid. I set the height of grid wrapper to a fixed value with scroll enabled and when the page loads last few rows are invisible until I scroll down. Does anyone found a fix for this?


https://user-images.githubusercontent.com/48117048/193790000-4c52017f-c67d-47b9-8cec-e3a113ce642e.mp4

**Comment by Matt-Jensen** [comment]
Was having this same problem.  This is a really hacky non-performant fix but you can set `disableVirtualScrolling={true}`

However looking into ensuring the [configured scrollable element](https://github.com/silevis/reactgrid/blob/2b14e7086c144b7c63f69bca2a6f3fa1f167ab4c/src/lib/Components/ReactGrid.tsx#L68) is correct wouldn't be a bad idea.  However I couldn't figure out how to set that.

**Comment by alonshmiel** [comment]
Hi @othman-19 , please close this issue if it's not relevant or add a codesandbox that reproduces it. Thanks!

**Comment by thuanhoang97** [comment]
I also face this issue with cells that have a span. Part of it will be hidden when I scroll. I have updated the example below. Does we any way to workaround util the issue got fixed?

https://codesandbox.io/s/reactgrid-liquidity-planner-forked-nk7dv2?file=/src/LiquidityPlanner.tsx

https://github.com/silevis/reactgrid/assets/38289417/0e44b56d-0f5a-4b51-aa00-3694a71bcddd

**Comment by alonshmiel** [comment]
Hi, Do you mean the header, right?

**Comment by thuanhoang97** [comment]
yes, the header cell with span. We really need `disableVirtualScrolling` feature on to use with large data.

**Comment by DLowHP** [comment]
Hi @thuanhoang97! 
I investigated your example and found [a workaround](https://codesandbox.io/s/reactgrid-liquidity-planner-forked-qjt2yf). 

Unfortunately your issue, as well as other mentioned in this discussion, require major changes in the grid renderer so it will take us significant amount of time. Because of that I think it will most likely be postponed until we fix the smaller bugs that we can move with faster. 

I hope you understand, take care!
