### ISSUE TITLE
When editing a cell, the first character is always in English

### ISSUE THREAD

**Issue by OlegGavr** [silevis/reactgrid#118]
**Describe the bug**
When I click on a cell whose type has letters and start writing something in another language, the first letter is always in English. And it's impossible to catch this event in the cell template on onChange or onFocusin handles if I use it custom.

**Expected behavior**
When I edit a cell, the first character should be in the same language as the keyboard layout

**Video example**

https://user-images.githubusercontent.com/52842037/180060132-8c8ac41d-9f18-4383-8e43-811cf2818f63.mov

**Comment by DLowHP** [comment]
Hi! I investigated this issue and found out that we will need keydown event's `key` property to retrieve proper character based on current user's language. I tried using current `keyCode` property (hence the label changes, sorry!), but I haven't been able to resolve this.
As this requires us to change the PublicModel I can't just replace this property, so I added an optional key property to keyDown event handler. From there you can get typed character by using `key.toLocaleLowerCase(navigator.language)`.

**Comment by qiufeihong2018** [comment]
Please tell me if this problem has been solved and how?
