### ISSUE TITLE
BorderProps color not implemented in CellRenderer

### ISSUE THREAD

**Issue by zliebersbach** [silevis/reactgrid#122]
**Describe the bug**
Setting the `color` property of `BorderProps` does not do anything. The renderer does not implement the `color` prop into the style of the cell.

**Current behavior**
Nothing.

**Expected behavior**
It works.

**Screenshots or gifs**
N/A

**Your environment details**
Current version.

**Comment by hunterwilhelm** [comment]
I added more details in #137

**Comment by hunterwilhelm** [comment]
The workaround for right now is to downgrade to v4.0.3
