### ISSUE TITLE
Cell Editor is rendering off of the spreadsheet

### ISSUE THREAD

**Issue by bryanj0410** [silevis/reactgrid#123]
I have the Spreadsheet inside a div container in my application, and it works fine on smaller screens. But on a larger screen, it renders the cell editor input off the spreadsheet. It looks as though it is calculating the offset based on the page, but then the position is being set off of the div it is contained in.

This is what it does on a larger screen:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/7966868/187241962-5677d002-8b94-44ed-b116-c13c18893265.png)

This is what is expected:
![Screen Shot 2022-08-29 at 9 48 29 AM](https://user-images.githubusercontent.com/7966868/187242079-aff32dbc-db15-4e1c-ac16-eae205ad0f70.png)

 - Device:  desktop
 - OS: Mac OS
 - Browser chrome

**Comment by hunterwilhelm** [comment]
I had a similar issue when one of my elements didn't forward the ref when using a portal. Since it looks like you have a sidebar, I would imagine you are using a portal. Make sure to include the parent-most ref so it can calculate where it needs to be on the screen.

**Comment by DLowHP** [comment]
Hi @bryanj0410! Did you manage to resolve the issue using Hunter's tip? If so please close the issue, otherwise it would really help if you could provide a MRE sandbox for I could investigate it and help you ;)

**Comment by bryanj0410** [comment]
@DLowHP I tried the suggestion and it still didn’t work for me, I ended up going a different route with the page.

**Comment by DLowHP** [comment]
Oh, I'm glad you've found a viable solution for yourself! I'm going to close this issue for now, as it doesn't seem to be very severe, but if you need any more help, I'd be happy to talk with you. Take care!
