### ISSUE TITLE
Disable select cell

### ISSUE THREAD

**Issue by nmdung28** [silevis/reactgrid#129]
There are some cells, I don't want to select. Is there a way to not select the cell?

**Comment by hunterwilhelm** [comment]
Say the user selects the surrounding cells of the unselectable cell. Should the unselectable cell be included in that range selection?

https://user-images.githubusercontent.com/71348224/195929882-9acce697-e2a3-4c0b-8e49-cbd3066774d7.mov

**Comment by DLowHP** [comment]
Hi @nmdung28! Could you provide further info, maybe with a visual representation? 
We're considering adding onSelection Start/Update/End props to allow users to react to selection changes and your case would be helpful for us to better match community needs.

**Comment by DLowHP** [comment]
I'm going to close this issue as it's inactive and we lack information. If you still want to request this let us know.
