### ISSUE TITLE
Cells not selectable

### ISSUE THREAD

**Issue by MichaelMatejko** [silevis/reactgrid#13]
I used the data from the README and cant select anything on first and third row.
![image](https://user-images.githubusercontent.com/6450011/83959663-e71d6e00-a87f-11ea-9259-557f14321efe.png)

**Comment by MichaelMatejko** [comment]
reason: rowIds in README are wrong.

**Comment by patryk0493** [comment]
Changed in [v.3.0.22](https://github.com/silevis/reactgrid/releases/tag/3.0.22)
