### ISSUE TITLE
Edit text cell issue

### ISSUE THREAD

**Issue by midotek** [silevis/reactgrid#130]
Describe the bug
When focus is on a cell start writing numbers on laptop using shift + number, the first element is not a number
PS: When i change cell to Number cell, put numbers as showing in video (shift + number ) is not possible, why i use Text cell

Expected behavior
When I edit a cell, the first character should be a number 

Video example

https://user-images.githubusercontent.com/49154587/195802634-93e371a3-5e37-4a5a-85b5-5d139efafab2.mp4

NextJs,Windows, chrome

**Comment by ChristoRibeiro** [comment]
@patryk0493 any feedback on that? Thanks.
