### ISSUE TITLE
How to set maxHeight (or maxRowsToDisplay?) for table?

### ISSUE THREAD

**Issue by tnrich** [silevis/reactgrid#131]
Hey,

I have a react grid like so::
```js
<ReactGrid
        stickyTopRows={1}
        rows={rows}
        columns={columns}
      />
```

How do I set a max height (or max num rows to show before scrolling) for the grid? I see it in the examples: 

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/2730609/196283377-80fac57c-c1da-4959-894e-fbcaf6aea252.png">

but I couldn't find a reference to it in the docs. 

Thanks!

**Comment by robertgutu** [comment]
You can find the source code for all examples here: https://github.com/silevis/reactgrid-website/tree/gh-pages-dev/src/samples/samplesSrc
For defining the height of the grid you should use a div wrapper like this: https://reactgrid.com/docs/4.0/2-implementing-core-features/8-embedding-on-website/
