### ISSUE TITLE
Only integer numbers for number cells

### ISSUE THREAD

**Issue by robertgutu** [silevis/reactgrid#132]
When editing a cell that is a number cell it allows only numbers and some characters such as "." "," "-". I was wondering if there is any way I can allow only numbers on editing number cells (without those characters) since I only need integer values.

**Comment by czerwiukk** [comment]
Reactgrid enables users to write and use their own cell templates.
If you need small changes like that, I'd encourage you to copy the NumberCell template code from our source code, apply desired changes and register it as a new cell template.

[https://reactgrid.com/docs/4.0/5-create-your-own-cell-template/](url)
