### ISSUE TITLE
Adding a new row

### ISSUE THREAD

**Issue by naiannegri** [silevis/reactgrid#133]
Hello,
I'm new in react and I'm using this component but I'm not finding any info about allowing the user to add new rows although I can see in the examples that its possible.

How can I set this??
Thanks.

**Comment by czerwiukk** [comment]
Hello,
everything you need is here.
In short, you map your data to the row interface and pass it to the ReactGrid component.
[https://reactgrid.com/docs/4.0/1-getting-started/](url)
