### ISSUE TITLE
How can I customize the table header?

### ISSUE THREAD

**Issue by lizhihao001** [silevis/reactgrid#134]
interface Column {
    /** Unique `Id` in all columns array */
    readonly columnId: Id;
    /** Width of each grid column (in default set to `150px`) */
    readonly width?: number;
    /** Allow column to change its position in grid,
     * default: `false` (row reorder implementation is on the developers side)
     */
    readonly reorderable?: boolean;
    /** Allow column to change is width in grid,
     * default: `false` (row resize implementation is on the developers side)
     */
    readonly resizable?: boolean;
}

There is no render method in the column interface, How can I customize the table header?
![image](https://user-images.githubusercontent.com/35721602/200382613-d394d01a-a04f-499d-838e-094820abcfcb.png)

**Comment by alonshmiel** [comment]
You can create a custom cell template and use it:
https://reactgrid.com/docs/4.0/7-api/0-interfaces/5-cell-template/

**Comment by alonshmiel** [comment]
Hi @lizhihao001 , can you close it?

**Comment by DLowHP** [comment]
I'm closing it because of lack of activity. If you need further help reopen this issue or create new.
