### ISSUE TITLE
copy paste is broken

### ISSUE THREAD

**Issue by vizibly-tech** [silevis/reactgrid#135]
I am unable to copy from excel and paste into the grid correctly. It is pasting into cells it shouldn't be pasting into. 

What's the ETA for the fix? 

https://www.loom.com/share/0e859f44555b4263ae6d5e5e098899a2

**Comment by czerwiukk** [comment]
Hello, thank you for reporting the issue.
I've analyzed the case and it looks like the issue is this exact example itself.
The column Q1 should be disabled and the values calculated from 3 months, but editing the Q1 column affects the months.
While pasting to months 1-3, pasting works as expected, as well as on the other examples.

**Comment by vizibly-tech** [comment]
Hi - thanks for clarifying that piece but there is still a problem in that it pastes a zero in the cell beneath.

**Comment by vizibly-tech** [comment]
here is it reproduced in a different example 

https://www.loom.com/share/6f83399f08c74db1a9b8a350b2a8af05

**Comment by vizibly-tech** [comment]
@czerwiukk any update?

**Comment by simonthomson** [comment]
I'm noticing this exact issue in my use case as well. It pastes one extra cell when pasting from excel

**Comment by simonthomson** [comment]
Some analysis of the clipboard data reveals that copied data from reactgrid does not have a trailing newline, while copied data from excel does. I can't be sure this is the cause but it seems likely

**Comment by styckalov** [comment]
Found a workaround for this issue. You can modify data from clipboard and pass new DataTransfer object to native grid pasteHandler

```
          <ReactGrid
            ref={(ref) => {
              if (!ref) return;
              const oldPasteHandler = ref.eventHandlers.pasteHandler;

              ref.eventHandlers.pasteHandler = (e) => {
                try {
                  const dataToPaste = e.clipboardData.getData('text/plain');
                  const htmlDataToPaste = e.clipboardData.getData('text/html');

                  if ( htmlDataToPaste.includes('xmlns:v="urn:schemas-microsoft-com:vml"') ) {
                    const slicedData = dataToPaste.slice(0, -2)
                    const dataTransfer = new DataTransfer();
                    dataTransfer.setData('text/plain', slicedData);
                    e.clipboardData = dataTransfer;
                  }

                  oldPasteHandler(e);
                } catch (e) {
                  console.error('There was an error on paste => ', e);
                }
              };
            }}
          />
```

**Comment by DLowHP** [comment]
Hello, I researched this problem, but unfortunately I was not able to reproduce it - could you provide a sandbox, and also preferably an Excel spreadsheet with the data you are copying highlighted?

**Comment by DLowHP** [comment]
I'm going to close this issue as it's inactive and we lack information. If you still need help with this let us know.
