### ISSUE TITLE
Border Color broken in v4.0.4

### ISSUE THREAD

**Issue by hunterwilhelm** [silevis/reactgrid#137]
**Describe the bug**
Border colors don't work anymore in v4.0.4 but they work in v4.0.3

**Current behavior**
Border color turns to grey and not showing in css in v4.0.4

**Expected behavior**
Border color should change to blue if I set it to blue.

**Screenshots or gifs**
```
{
    rowId: idx,
    height: 60,
    cells: [{ type: "flag", text: flag.isoCode, style: {border: {left: {color: "blue"}}} }]
  }
```

v4.0.4
<img width="167" alt="image" src="https://user-images.githubusercontent.com/71348224/203436818-ebbb8ce6-8fcd-452f-87d2-7e580d56547d.png">

v4.0.3
<img width="193" alt="image" src="https://user-images.githubusercontent.com/71348224/203436872-6c3ed59d-18fc-40a2-8d4c-b53ca8e39a29.png">

**Your environment details**
 - Device: Desktop
 - OS: Windows/Mac
 - Browser Chrome/Firefox

**Comment by afoxer-com** [comment]
Same.

**Comment by DLowHP** [comment]
I added this property to cell renderer, it should work now ;)
