### ISSUE TITLE
[Feature Request] Get the copied content's data when pasting

### ISSUE THREAD

**Issue by codniel** [silevis/reactgrid#138]
**Describe the bug**
Not pasting correctly, and is heavily dependent on the existing number of rows.

**Current behavior**
After copy-pasting a certain number of rows/cells to the table, only one row is added at a time. `onCellsChanged` fire but only contains the exact number of rows and cells that exists on your data.

**Expected behavior**
Should at least give us the copied contents for us to prepare the number of rows before firing `onCellsChanged`

**Screenshots or gifs**
Notice how I copy a number of rows on the first tab, then pasting it on the next tab, and how I went on to spamming `ctrl-v` to paste all rows
https://www.loom.com/share/993173e382594cdb86e52176121be17e

Here is also a screenshot on what is being changed on `onCellsChanged`
Notice how it doesn't contain any other details on what is being pasted.
![react-grid](https://user-images.githubusercontent.com/61054429/203696329-9b9a12b5-1e45-4f11-b401-6a9b1d3a7cf5.PNG)

**Your environment details**
 - Device:  PC
 - OS: Windows
 - Browser: Chrome, Safari, IE, Firefox, etc.

**Comment by alonshmiel** [comment]
Hi, I'm not sure that I understand everything but copy-paste feature can handle multiple cells. You can try it here:
https://codesandbox.io/s/reactgrid-playground-ohywn7
Please copy five cells (0-4) in the first column (cell index: 5).

**Comment by DLowHP** [comment]
I'm closing it because of lack of activity. If you need further help reopen this issue or create new.

We might consider different solution for handling copy/cut/paste, but it would most likely require significant changes so it will be postponed until new major version. I hope you understand, take care!
