### ISSUE TITLE
dynamically add and remove rows with undo/redo functionality 

### ISSUE THREAD

**Issue by Nikodem98** [silevis/reactgrid#142]

**Comment by DLowHP** [comment]
Hi! You could try to implement "dynamic rows" on undo/redo by ~~not only changing the data but also the structure of your source array. Take a look at [the docs](https://reactgrid.com/docs/4.0/2-implementing-core-features/9a-undo-redo-feature/).~~ - I tried this and after couple iterations I went through I'd just suggest you use a state management library (such as [Jotai](https://jotai.org/)). It will be much easier to implement and manage than implementing all of this by yourself. 
Edit: You'd still need to modify the rows array and grid's data, but it will most likely be much easier than doing all this from scratch.

I'm closing this issue - if you'd need further help reopen this issue or create new.
