### ISSUE TITLE
Cannot copy paste if cell is dropdown

### ISSUE THREAD

**Issue by ethananhh** [silevis/reactgrid#144]
**Describe the bug**
Cannot copy paste if cell is dropdown

Has anyone encountered the same error, please help me

**Comment by alexpunct** [comment]
Yeah I have the same. Looks like on their example on the site they use a custom template with a native select. It would be nice if we had the source code of [that page](https://reactgrid.com/examples/?example=customization)

**Comment by alonshmiel** [comment]
Hi, you can create [custom cell template](https://reactgrid.com/docs/4.0/7-api/0-interfaces/5-cell-template/) and control everything.

Does it help?

**Comment by DLowHP** [comment]
This was fixed by #195, if you encounter any other issues please inform us :)
