### ISSUE TITLE
Can i get list of data when selected in range mode?

### ISSUE THREAD

**Issue by PTOAKKY** [silevis/reactgrid#151]
Can i get data of selected item (range / row / column) from callback or anything ?

expected -> get data to display summary values when user selected range of data in table.

**Comment by rundro** [comment]
Also looking for an "on selected" handler, I want to modify the cells style (bg color) based on the range of cells being selected. Any way to do this?

**Comment by alonshmiel** [comment]
Hi,
Another developer asked this feature so I guess it's important for more developers.
I will start working on it after I will have more night time (first son in my family).

**Comment by DLowHP** [comment]
Hi! We've added `onSelectionChanged` and `onSelectionChanging` callbacks - that give you the Range selected - in #184. I'll close this issue but if you need anything else feel free to reach out to us 😄
