### ISSUE TITLE
Is reactgrid supports virtualized lists?

### ISSUE THREAD

**Issue by GlennMiller1991** [silevis/reactgrid#152]
Data can contains a lot of rows, 10 000 or even more. Without any handling response time is too high. Is it way to improve user experience?

**Comment by alonshmiel** [comment]
Can you please add a link with the code that illustrates the issue?
I tried with 10,000 rows and it works fine: there is a virtualization and the update works fast.

**Comment by DLowHP** [comment]
I'm closing it because of lack of activity. If you still need help please provide a sandbox that reproduces your example. Please also take a look at my [comment in #126](https://github.com/silevis/reactgrid/issues/126#issuecomment-1667579702) related to your issue that explains more.
