### ISSUE TITLE
Empty rows are displayed when scrolling quickly up and down

### ISSUE THREAD

**Issue by daniel-dvorak** [silevis/reactgrid#153]
**Describe the bug**
When you have lots of rows (e.g. 500) loaded in the table and you start scrolling quickly up and down (by using the scroll bar), the rows in the table are invisible, so the user can’t find the searched row so easily.
This happens only when virtual scrolling is enabled. But disabling the virtual scrolling makes significant performance issues in some cases. 

**Current behavior**
When you scroll up and down quickly, the rows in the table are temporarily invisible, so the user is unable to navigate through the table so easy.

**Expected behavior**
We should be able to see values in the table when scrolling quickly.

**Your environment details**
 - Device:  MacBook
 - OS: macOS
 - Browser Chrome
 - Happens on all devices/OS/browsers

**Comment by alonshmiel** [comment]
Can you add a link with an example?

**Comment by alon-shmiel-sage** [comment]
Hi @daniel-dvorak , any update? If not, please close this issue.

**Comment by alonshmiel** [comment]
@fellmann , please close this issue. It's reproduced also in react-virtualized library.
