### ISSUE TITLE
How to implement Sort or Filter feature on header

### ISSUE THREAD

**Issue by johnvinosh** [silevis/reactgrid#154]
**Describe the bug**
No Sort or Filter feature

**Current behavior**
No Sort or Filter feature

**Expected behavior**
Sort and Filter Rows

**Comment by alonshmiel** [comment]
You can create a custom cell for every cell of the header and make any filter/sort you wish:
https://reactgrid.com/docs/4.0/5-create-your-own-cell-template/

**Comment by alon-shmiel-sage** [comment]
Hi @johnvinosh , please close this issue if my answer makes sense :)
