### ISSUE TITLE
Cannot read properties of undefined (reading 'scrollableElement')

### ISSUE THREAD

**Issue by duongductrong** [silevis/reactgrid#158]
**Describe the bug**
Cannot read properties of undefined (reading 'scrollableElement')

**Current behavior**
Doing same demo https://codesandbox.io/s/reactgrid-getting-started-0754c?from-embed in react 18

**Expected behavior**
It will work same the demo

**Screenshots or gifs**
<img width="1680" alt="Screen Shot 2023-03-19 at 19 46 35" src="https://user-images.githubusercontent.com/39333905/226176101-6c49ee9a-46c1-4743-b30d-722a2fa0f451.png">

**Your environment details**
 - Device:  [macos bigsur]
 - Browser: Chrome
 - Both: React 18 + Vite and Remix.js

**Comment by alon-shmiel-sage** [comment]
Your demo doesn't use react 18.
Please update your link and write the steps to reproduce.

**Comment by romanstetsyk** [comment]
I've got the same issue. Here is a [codesandbox](https://codesandbox.io/p/sandbox/infallible-ellis-6zs5v0?file=%2Fsrc%2FApp.tsx) that uses react 18.2.
To reproduce, the bug, double-click in any cell. The code in `App.tsx` is a copy-paste from the [docs](https://reactgrid.com/docs/4.0/1-getting-started/).

**Comment by alon-shmiel-sage** [comment]
@romanstetsyk ,
I copied and pasted from the docs and pasted it here:
https://playcode.io/1323277

Can you please reproduce it? I couldn't.

**Comment by romanstetsyk** [comment]
@alon-shmiel-sage The bug appears only if I wrap the `<App/>` with `StrictMode`. It looks like it's a strict mode that's causing the issues.
Were you able to reproduce it in the codesandbox I linked above?

**Comment by alon-shmiel-sage** [comment]
Thanks, checking..

**Comment by alon-shmiel-sage** [comment]
Reproduced.. Will try to figure out.

**Comment by alon-shmiel-sage** [comment]
OK so I see that we get an event with top and left props but doesn't have state property.
So I tried to figured it out and found this:
"We're currently building the next version of ReactGrid from the ground up and decided to leave this topic in the current state. If you want to use the current version, disable the strict mode while using React 18."

https://github.com/silevis/reactgrid/issues/87

Sorry..

**Comment by romanstetsyk** [comment]
Thanks for looking into this! There's hope this project is not abandoned :)

**Comment by duongductrong** [comment]
Thanks, everyone, this project is awesome, and I hope it is complete soon

**Comment by alon-shmiel-sage** [comment]
Hi @duongductrong , please close this issue :)

**Comment by duongductrong** [comment]
> Hi @duongductrong , please close this issue :)

sure 👍

**Comment by imkitukov** [comment]
> 

@alon-shmiel-sage 
Do you know where we can track the progress of the completely new ReactGrid version from the ground?

**Comment by alon-shmiel-sage** [comment]
@imkitukov , I'm sorry but no.. I just tried to help some developers with some issues but I don't know the creators of Silevis.
