### ISSUE TITLE
Chinese input method cannot automatically get the focus

### ISSUE THREAD

**Issue by galenzh** [silevis/reactgrid#159]
**Describe the bug**
When I select a cell and try to input some chinese text it can't get focus. I must press enter to get foucs by myself.

**Screenshots or gifs**

![Bug](https://user-images.githubusercontent.com/3645554/227418664-c9d14f79-2636-4bd6-a966-00457781e7d6.png)

**Your environment details**
 - Device:  PC
 - OS: Win 10
 - Browser: Chrome

**Comment by DLowHP** [comment]
Hi @galenzh! This has been fixed by #185 which introduced compositionEnd event handler to text-based cells. Check it out and let us know if you find other issues. Take care!
