### ISSUE TITLE
onCellsChanged handler is not triggered when editing the last row of a grid

### ISSUE THREAD

**Issue by HallOfSame** [silevis/reactgrid#160]
**Describe the bug**
When using a grid with an `onCellsChanged` handler, the handler is not called when making edits in the bottom row of the grid.

**Current behavior**
Cells in other rows properly call `onCellsChanged` but edits in the bottom row do not trigger the cell template `update` method or the `onCellsChanged` handler.

**Expected behavior**
`onCellsChanged` should be triggered when editing cells in the bottom row.

**Screenshots or gifs**

**Your environment details**
 - Device:  Desktop
 - OS: Windows 11
 - Browser Firefox 102.9

I think this is due to the `tryAppendChange` call being triggered inside of `focusLocation`. 

In `handleKeyDown` the state is updated with `moveFocusDown` when Enter is pressed. `withMoveFocusDown` calls `getFocusLocationToDown`. This tries to return the cell below the one that is currently focused, which doesn't exist, so it returns `undefined` instead. This means that `focusLocation` never gets called and so `tryAppendChange` isn't called either.

**Comment by alonshmiel** [comment]
Hi @HallOfSame , can you please send a link that reproduces it?
It works fine for me here: https://codesandbox.io/s/reactgrid-playground-ohywn7
I succeeded to edit the last row (sticky row) and the previous row (not sticky), and onCellsChanged was called.
(windows 10, Chrome).

**Comment by HallOfSame** [comment]
Hmmm yeah not sure why it's happening locally then, must be an issue on my end. Have a few custom cell templates so it might be an issue somewhere in there.

**Comment by Sruli-RD** [comment]
Did you ever find the cause?

**Comment by alonshmiel** [comment]
Hi @Sruli-RD , if you have a link that reproduces it, please share it so I will try to find the cause.
