### ISSUE TITLE
Liquidity Planner bug

### ISSUE THREAD

**Issue by foghorn-hash** [silevis/reactgrid#162]
**Describe the bug**
I try to use Liquidity Planner Example in my App and StickyRow on left do not work like on your example page.

**Current behavior**
Lest StickyRow do not be in right position.

**Expected behavior**
I want it hovers over the grid.

**Screenshots or gifs**
(https://www.i4ware.fi/downloads/2023-05-10.png)

**Your environment details**
 - Device:  decktop
 - OS: Windows 11
 - Browser Firefox

**Comment by alonshmiel** [comment]
Hi,
You wrote left stickyRow so I am not sure I understand.
Did you mean left sticky column or top sticky row?

Can you please add the relevant code?

**Comment by foghorn-hash** [comment]
Okay here is minimal code:

`return (
    <>
      <div className="liquidity-planner-app">
        <ReactGrid
          rows={rows}
          columns={columns}
          onCellsChanged={handleChanges}
          stickyTopRows={1}
          stickyBottomRows={1}
          stickyLeftColumns={1}
          stickyRightColumns={1}
        />
      </div>
    </>
  );`

And my CSS code:

`@import url("https://fonts.googleapis.com/css2?family=DM+Sans&display=swap");

.reactgrid {
  position: relative !important;
}

.reactgrid-content {
  position: absolute !important;
  background-color: transparent;
}

.rg-pane {
  background-color: transparent;
}

.liquidity-planner-app {
  font-family: "DM Sans", sans-serif;
  color:#666;
}

.liquidity-planner-app .reactgrid .rg-cell:not(.rg-cell-nonEditable):after {
  position: absolute;
  top: 5px;
  left: 5px;
  width: 10px;
  height: 10px;
  content: "";
  background: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAOCAYAAAAbvf3sAAAACXBIWXMAABYlAAAWJQFJUiTwAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAACzSURBVHgBnZCNDcIgEIXLlQEYwU6gbFAmUCdwBTcyjuAEugEmLOAILAD4jsSEJrWnvYSEg+/dz+u6P0MtfXrvTd/3h5TSw1r7WhQwrLW+l1J2SCNEDqKnEuANg0R0VkrtcR9IqMxhINgij+gQaQ7OORuuBuiGHWonvB2ZoTkYx/HcXLmdnzn9DW5y+3GouiTAroVrB/aZF8TnIMGTHSAcJXgiQFwkeFWoEMKIHU6/wLD3+gbQmKMY0ysadgAAAABJRU5ErkJggg==")
    center;
  background-size: contain;
}

.liquidity-planner-app .disabled {
  color: #666;
}

.liquidity-planner-app .reactgrid-content .rg-pane .rg-cell {
  padding: 8px 16px;
  font-size: 12px;
}

.liquidity-planner-app .padding-left-lg {
  padding-left: 24px !important;
}

.liquidity-planner-app .justify-content-center {
  justify-content: center;
}

.liquidity-planner-app .justify-content-end {
  justify-content: flex-end;
}

.liquidity-planner-app .align-items-end {
  align-items: flex-end !important;
}

.liquidity-planner-app .font-bold {
  font-weight: 600;
}

.liquidity-planner-app .text-red {
  color: #cf1322;
}

.liquidity-planner-app .text-blue {
  color: #2797ff;
}

.liquidity-planner-app .text-green {
  color: #107c41;
}

.liquidity-planner-app .light-green-bg {
  background-color: #e7f2ec;
}

.liquidity-planner-app .text-md {
  font-size: 14px !important;
}

.liquidity-planner-app .text-lg {
  font-size: 16px !important;
}

.liquidity-planner-app .rg-cell {
  background-color: transparent !important;
}

.liquidity-planner-app .rg-celleditor {
  font-size: 12px;
  padding: 8px 16px;
  border-width: 1px;
  box-shadow: 0px 0px 8px #2797ff;
  background-color: black;
}

.liquidity-planner-app .rg-celleditor input {
  font-family: "DM Sans", sans-serif;
  color: #e7f2ec;
  border: 0px transparent solid;
  background-color: transparent;
}

.liquidity-planner-app .reactgrid-content .rg-pane .rg-cell-focus {
  border-color: #2797ff;
  border-width: 2px;
}

.liquidity-planner-app .reactgrid-content .rg-pane .rg-cell-focus {
  border-color: #2797ff;
  border-width: 2px;
}

.rg-pane-left {
  background-color: black !important;
}

.rg-pane-right {
  background-color: black !important;
  border-left: 1px #e7f2ec solid;
  border-right: 1px #e7f2ec solid;
}

.rg-pane-top {
  position: relative;
  background-color: black !important;
  border-bottom: 1px #e7f2ec solid;
}`

**Comment by foghorn-hash** [comment]
I mean this: stickyLeftColumns={1} and it is not overlay the grid so whole grid come to be too wide.

**Comment by alonshmiel** [comment]
I created the grid with your css (assets/styles.css) and it works fine in my mac.

Does it work for you?
https://codesandbox.io/s/determined-water-jr0x6j

**Comment by foghorn-hash** [comment]
Thanks but it is not work yet. Please see my screen-capture video on YouTube: (https://youtu.be/ijP4XpKRuRE)

**Comment by alonshmiel** [comment]
I see but does it work here?
https://jr0x6j.csb.app/

I tried it on Windows also and it works for me (version 3.1.17).

If the above link works for you, I suggest you to remove any css that you have and see if the problem exists.
If not, can you please reproduce it and send me a link?

**Comment by foghorn-hash** [comment]
Hmm.. my App is here (https://saas.i4ware.fi/).

I is React and TypeScript project wit Laravel 9 back-end and is very large project.

And Source Code is here but I am not set it to public: (https://bitbucket.i4ware.fi/)

I use XAMPP in my local machine with Windows 11 OS for developing this App.

**Comment by foghorn-hash** [comment]
And yes it works fine in your example.

**Comment by alonshmiel** [comment]
Can you send me an email with credentials so I can login?

**Comment by foghorn-hash** [comment]
Okay I can send you private message but I don't know how to do it.

**Comment by alonshmiel** [comment]
Please let me know after you sent it..

**Comment by foghorn-hash** [comment]
I am now sent you an email.

**Comment by alonshmiel** [comment]
OK so I am not sure but please check it:
There is no scroll for your grid but for the whole window.

**For your case:**
please add `overflow-x: auto;` to your element with the class of `liquidity-planner-app`.

**For a generic case:**
You need to wrap the grid with a div that has a smaller width than the grid + overflow-x: auto.

```
<div class="grid-container">
   <ReactGrid>...</ReactGrid>
</div>
```

and add this style:

```
.grid-container {
      width: 800px; // or whatever you wish
      overflow-x: auto;
}
```

I guess that it should work but please let me know.

**Comment by foghorn-hash** [comment]
Yes now it works.

**Comment by alon-shmiel-sage** [comment]
Hi, please close your issue..

**Comment by foghorn-hash** [comment]
This issue is now resolved.
