### ISSUE TITLE
Implementing checkbox inside cells

### ISSUE THREAD

**Issue by kazmi066** [silevis/reactgrid#163]
Hi! Is there any implementation for implementing checkbox inside cells for boolean values

**Comment by alonshmiel** [comment]
Hi,
You can create a cell with type of 'checkbox'.

`cells: [
      { type: "number", value: door.id },
      {
        type: "checkbox",
        checked: door.isOpen
      }
    ]`

Here are the details:
https://reactgrid.com/docs/4.0/4-cell-templates/2-CheckboxCell/

And this is an example:
https://codesandbox.io/s/silevis-reactgrid-working-checkbox-example-j6266z

Please close your issue if it answers your question.

**Comment by kazmi066** [comment]
Thanks
