### ISSUE TITLE
how to listen for past or on Blur from the cell ?

### ISSUE THREAD

**Issue by ramusesan** [silevis/reactgrid#164]
Hi I wanted to read the values from one on cell onBlur from the Cell and send them to an API.other use cases 

1. I may select the multiple rows/columns and past values from the Excel sheet

how can i watch for onBlur or onPaste or onUndo and reDo

**Comment by alonshmiel** [comment]
Hi,
When there is an update on a cell, onCellsChanged is called.
Can you use it?
In addition, for undo/redo, you should use: https://reactgrid.com/docs/4.0/2-implementing-core-features/9a-undo-redo-feature/

Regarding to your second question:
https://reactgrid.com/docs/4.0/2-implementing-core-features/4a-selections/

**Comment by DLowHP** [comment]
I'm going to close this issue due to lack of activity. If you need further help reopen this issue or create new.
