### ISSUE TITLE
Upgrade library to use with react 18

### ISSUE THREAD

**Issue by DVGY** [silevis/reactgrid#165]
This is one of best react grid library I have seen. 
Is there any upgradation roadmap that we can follow ?

**Comment by bushmango** [comment]
We've had no issues with React18 so far, we've just had to force install with npm i --force

**Comment by bushmango** [comment]
Oh, I forgot to mention, we did have to turn React 18 strict mode off

**Comment by DVGY** [comment]
> 

This is an issue for us, we can't turn react strict mode off

**Comment by alonshmiel** [comment]
Hi,
I know a lot of developers were waiting for upgrading this amazing library to React 18.

So I have good news!!
I forked this library to my account and made the relevant changes in order to make it work in React 18.
I have tested it on my Mac but please test it also and verify everything works.

I updated React to 18, node-sass to sass and changed the config of rollup to use sass instead of node-sass.
So I succeeded to use this library with strict mode:

```
<React.StrictMode>
      <Grid...../>
</React.StrictMode>
```

I will make a PR for this library so the maintainers will be able to merge it to their library.

You can install my library by:

`npm install git+https://github.com/alonshmiel/reactgrid.git`

And then you can use the CSS by:

`@import "@silevis/reactgrid/dist/styles.scss";
`
And the JS by:
```
import {
  ReactGrid,
  getCellProperty,
  getCharFromKeyCode,
  inNumericKey,
  isAllowedOnNumberTypingKey,
  isAlphaNumericKey,
  isNavigationKey,
  isNumpadNumericKey,
  keyCodes,
} from "@silevis/reactgrid/dist/core";
```

I faced with an error when using strict mode (can't access property "scrollableElement", t is undefined)
It was because of the strict mode.
React StrictMode calls reducer two times to eliminate any side-effects.
This error was thrown because the reducer didn't store the state so the second call didn't have the old state that it needs. That's why I stored the state.

Please open any issue you face with,
and I hope to maintain this library as much as I can since I'm gonna have a new baby boy in my family 💚

**Comment by DVGY** [comment]
> Hi, I know a lot of developers were waiting for upgrading this amazing library to React 18.
> 
> So I have good news!! I forked this library to my account and made the relevant changes in order to make it work in React 18. I have tested it on my Mac but please test it also and verify everything works.
> 
> I updated React to 18, node-sass to sass and changed the config of rollup to use sass instead of node-sass. So I succeeded to use this library with strict mode:
> 
> ```
> <React.StrictMode>
>       <Grid...../>
> </React.StrictMode>
> ```
> 
> I will make a PR for this library so the maintainers will be able to merge it to their library.
> 
> You can install my library by:
> 
> `npm install git+https://github.com/alonshmiel/reactgrid.git`
> 
> And then you can use the CSS by:
> 
> `@import "@silevis/reactgrid/dist/styles.scss"; ` And the JS by:
> 
> ```
> import {
>   ReactGrid,
>   getCellProperty,
>   getCharFromKeyCode,
>   inNumericKey,
>   isAllowedOnNumberTypingKey,
>   isAlphaNumericKey,
>   isNavigationKey,
>   isNumpadNumericKey,
>   keyCodes,
> } from "@silevis/reactgrid/dist/core";
> ```
> 
> I faced with an error when using strict mode (can't access property "scrollableElement", t is undefined) It was because of the strict mode. React StrictMode calls reducer two times to eliminate any side-effects. This error was thrown because the reducer didn't store the state so the second call didn't have the old state that it needs. That's why I stored the state.
> 
> Please open any issue you face with, and I hope to maintain this library as much as I can since I'm gonna have a new baby boy in my family 💚

@alonshmiel I am also looking for contribution. I was going through library found out that lot of files do not have comments, they don't explain what is the use of the `xyz` component.

**Comment by alonshmiel** [comment]
Cool! 💯 
I know but debug answers everything..

**Comment by DVGY** [comment]
https://github.com/silevis/reactgrid/pull/167

<img width="726" alt="image" src="https://github.com/silevis/reactgrid/assets/46158826/5188ad90-eb2d-4512-9ebd-95c7fb2131a4">

I did `npm install git+https://github.com/alonshmiel/reactgrid.git`

**Comment by alon-shmiel-sage** [comment]
I guess you need to set the declaration file.
It's located in:
@silevis/reactgrid/dist/reactgrid.d.ts

**Comment by fellmann** [comment]
@alonshmiel is there any news on migrating your changes to this repository?

**Comment by alonshmiel** [comment]
Hi, my baby was born this week so I guess I need more night time..
I hope that I will succeed to make the PR this week..

**Comment by DVGY** [comment]
> Hi, my baby was born this week so I guess I need more night time.. I hope that I will succeed to make the PR this week..

Congratulations !!!!!!

**Comment by fellmann** [comment]
> Hi, my baby was born this week so I guess I need more night time.. I hope that I will succeed to make the PR this week..

Congratulations! Take your time :)

**Comment by DVGY** [comment]
> @silevis/reactgrid/dist/reactgrid.d.ts

```
import { ReactGrid } from "@silevis/reactgrid/dist/core";
import { Row, Column } from "@silevis/reactgrid/dist/reactgrid";

```
This solved my problem. Thanks

**Comment by alonshmiel** [comment]
Hi @fellmann ,
This is the PR of the upgrade to React 18
https://github.com/silevis/reactgrid/pull/177

After this PR, I have one-two more PRs that fixes some issues (i.e. esc key doesn't cancel the change when editing a cell).

**Comment by fellmann** [comment]
@alonshmiel Seems I succeeded to publish Reactgrid 4.0.5 at https://www.npmjs.com/package/@silevis/reactgrid

Could you please verify everything works as expected?

**Comment by alonshmiel** [comment]
Hi, it looks fine for me and I succeeded to use React.strictMode :)
(I created an app that uses @silevis/reactgrid)

In addition, I changed the values, copy-paste, ctrl-z + ctrl-y.

![image](https://github.com/silevis/reactgrid/assets/1051603/93dfa31f-c3e7-40cd-8502-edaf6fdc741e)

**Comment by alonshmiel** [comment]
Hi @fellmann ,
In a second thought, don't we need to deploy it as a minor update instead of a patch update?

**Comment by fellmann** [comment]
Maybe, but I'm afraid it's too late for that 🙂 I just used the existing pipelines for versioning and deployment.
On the other hand, I don't see any new features, and the new version behaves exactly as the old version, so "internal update" is not wrong I think.
Hope everything works as it should, I will close the issue.

**Comment by alon-shmiel-sage** [comment]
[heart]         Shmiel, Alon reacted to your message:
________________________________
