### ISSUE TITLE
Is this repository still maintained?

### ISSUE THREAD

**Issue by fellmann** [silevis/reactgrid#169]
There are no commits since June 22, issues and PRs are not answered by maintainers.

For discussion:
1. Current maintainers should continue to work on this repository
2. New maintainers could be added to this repository
3. Or a fork like https://github.com/alonshmiel/reactgrid could be used for future development

@alonshmiel fyi

**Comment by nmdung28** [comment]
I read a reply from the maintainer of this lib that they gave up and switched to developing another lib

**Comment by alonshmiel** [comment]
Hi @nmdung28 , where did you read it?

From my side, I created a npm package and will add more options to this library (such as a callback of onChangeSelection).

**Comment by fellmann** [comment]
Probably this comment: https://github.com/silevis/reactgrid/issues/87#issuecomment-1161675158

**Comment by DVGY** [comment]
> Probably this comment: [#87 (comment)](https://github.com/silevis/reactgrid/issues/87#issuecomment-1161675158)

https://github.com/silevis/reactgrid/pull/167

I think some work is in progress

**Comment by fellmann** [comment]
So I had a conversation with the project owner. This is the status:

- They are planning to continue this repository.
- A new version of ReactGrid is actively worked on, but will take some more months.
- As soon as the foundations have been laid, it will be published here.
- To provide maintenance until then, new maintainers could be added here.

@alonshmiel  Would you be willing to contribute your changes to this repository? I think it would be preferable to continue the project here than to make all users move.

**Comment by MichaelMatejko** [comment]
Guys thanks for your help. I'll give @fellmann the admin rights to this repo. He will be able to add additional contributors who want to work on the open issues.

**Comment by alonshmiel** [comment]
Hi @fellmann , sure!
I hope that I will have some time this weekend to open a PR with React 18 upgrade..
In addition, I am not sure about the procedure but I would like to be a maintainers for this amazing repo.
