### ISSUE TITLE
example for Cell which make an api request and render dropdown menu options, 

### ISSUE THREAD

**Issue by DVGY** [silevis/reactgrid#170]
Is there any example for AJAX Cells, which renders dropdown menu upon fetching some data from API?

**Comment by alonshmiel** [comment]
Do you mean that the dropdown values are taken from ajax?
OR:
Do you mean that selecting dropdown value will make an ajax call to render the grid?

**Comment by DVGY** [comment]
> ill make an ajax call

Suppose there is a cell. If user clicks on that cell, it should make an api call and show some dropdown values, or if user wants to type inside the cell, it should make an api call based to search text and render drop down value. 



[autocomplete-input.webm](https://github.com/silevis/reactgrid/assets/46158826/e32bc55e-7f76-46e9-a290-426447a2932f)

Update: Obviously maybe i will need to make custom cell for it, is there any example ?

**Comment by alonshmiel** [comment]
Hi @DVGY 
I think you can use: onFocusLocationChanged or onFocusLocationChanging:
https://reactgrid.com/docs/3.1/7-api/0-interfaces/1-reactgrid-props/

Than you can make your api calls and update the grid data as you wish.

**Comment by alonshmiel** [comment]
Hi, this is an example of custom cell template:
https://codesandbox.io/s/reactgrid-creating-new-cell-template-forked-58pj6p?file=/src/index.tsx

And this is the tutorial in the demo:
https://reactgrid.com/docs/4.0/5-create-your-own-cell-template/

If it makes sense, can you please close this issue?
