### ISSUE TITLE
Any support for spanned column header

### ISSUE THREAD

**Issue by kazmi066** [silevis/reactgrid#172]
**Describe the bug**
I have already created spreadsheets now with reactgrid. I got a use case in which I need a multiple span header for some columns acting as a parent head. I've attached an example screenshot of what I want. I need something like `Fasting Value` here

**Screenshots or gifs**
![qfS9Y](https://github.com/silevis/reactgrid/assets/37541648/4ca4cecb-6642-40a8-9fe2-3f29b4da896a)

**Comment by alonshmiel** [comment]
Hi, 
You can use colspan and rowspan properties.

https://reactgrid.com/docs/4.0/2-implementing-core-features/9e-cell-span/

Something like:
https://codesandbox.io/s/kind-silence-4rws58

**Comment by kazmi066** [comment]
@alonshmiel Thanks that helps
