### ISSUE TITLE
is it possible to range select a cell, and populate the same values in the cell below ?

### ISSUE THREAD

**Issue by DVGY** [silevis/reactgrid#174]
<img width="394" alt="image" src="https://github.com/silevis/reactgrid/assets/46158826/55db1d51-09a8-4b46-8bad-50e7cf886bcc">
<img width="87" alt="image" src="https://github.com/silevis/reactgrid/assets/46158826/c142d279-3386-46f0-bfb4-0aabf8c265a2">
<img width="88" alt="image" src="https://github.com/silevis/reactgrid/assets/46158826/09a202a4-771d-42ba-9a66-e01d9d72eac4">

I selected a cell, by placing my mouse on bottom right corner, and dragged it vertically downward to selected few more cell, and then all the values in cells are same. Is this possible in reactgrid ?

**Comment by alonshmiel** [comment]
Yes, please take a look here:

https://reactgrid.com/docs/4.0/2-implementing-core-features/4b-fill-handle/
