### ISSUE TITLE
Buggy DropDownCell 

### ISSUE THREAD

**Issue by DVGY** [silevis/reactgrid#175]
[codesandbox](https://codesandbox.io/p/sandbox/cool-thunder-5hvcwq?file=%2Fsrc%2FApp.tsx%3A86%2C9-86%2C16)

1. DropDownCell is slow : If i try to press down arrow key continuously, it takes few seconds to go 
2. Change the value in Gender column of any column, and then scrolling the sheet down fast, and scroll up fast, you will see, the value inside the cell is gone, it's empty

My questions 
1. is it possible to apply fill handle to dropdown cell too ?
2. Is is possible to extend the feature of dropdown cell so that, it can behave as combobox. (Apart from selecting values, user can also enter random text) ?

Thanks

**Comment by alonshmiel** [comment]
Hi,
You have issue with isOpen that gets its old value on cell updated.
In addition, you didn't use selectedValue. InputValue is the value when user is typing.

Here is a dropdown example (but please read until the end):
https://codesandbox.io/s/silevis-reactgrid-working-dropdown-example-ow9j2c

Regarding to your questions, I suggest you to implement a combobox by a cell template:
https://reactgrid.com/docs/4.0/7-api/0-interfaces/5-cell-template/

Here is an example:
https://reactgrid.com/docs/4.0/5-create-your-own-cell-template/

Please note that there is an error in the view of the example but if you try it by yourself, you see it works.
That you can have the answers of your both questions.

**Comment by DVGY** [comment]
> Hi, You have issue with isOpen that gets its old value on cell updated. In addition, you didn't use selectedValue. InputValue is the value when user is typing.
> 
> Here is a dropdown example (but please read until the end): https://codesandbox.io/s/silevis-reactgrid-working-dropdown-example-ow9j2c
> 
> Regarding to your questions, I suggest you to implement a combobox by a cell template: https://reactgrid.com/docs/4.0/7-api/0-interfaces/5-cell-template/
> 
> Here is an example: https://reactgrid.com/docs/4.0/5-create-your-own-cell-template/
> 
> Please note that there is an error in the view of the example but if you try it by yourself, you see it works. That you can have the answers of your both questions.

I don't know If I am doing something wrong. I copied your codesanbox example and added more person data.
[added more records](https://codesandbox.io/s/silevis-reactgrid-working-dropdown-example-forked-ktry8r?file=/src/App.tsx)

I added more data, like 300 rows, lol !!! 

DropDownCell is slow : If I try to press down arrow key continuously, it takes few seconds to go. 
Change the value in Gender column of any column, and then scrolling the sheet down fast, and scroll up fast, you will see, the value inside the cell is gone, it's empty

Both of these problem still persist. Also I compared my codesandbox with your example these two lines are similar

```js
} else if (change.type === "dropdown") {
      dataRow[fieldName] = change.newCell.inputValue as never;
      // CHANGED: set the isOpen property to the value received.
      dataRow.isOpen = change.newCell.isOpen as never;

```

So this is what happen, 
. If I click on a cell in Gender column and **do not select and value** from drop down and clicking outside the grid. It will set the value of the cell (inputValue and SelectedValue) to `undefined`

Well I don't know what to do. Can you suggest something ? Like I am confused when to use inputValue and when to use SelectedValue

**Comment by DVGY** [comment]
I think dropdown cell useEffect is running twice

**Comment by alonshmiel** [comment]
Hi,
your issues are not related to react-grid but your implementation.
For example:
1. performance issue: getRows function iterates all the people in O^2 although you can make it in O.
I suggest you to store the dropdown values in a Set.
2. people variable is overidden again and again when component is rendered. You need to change your implementation.
I suggest you to ask it on Stackoverflow but if you think there is a bug in React-Grid, please let me know..

**Comment by DVGY** [comment]
@alonshmiel 
Update on 

> Change the value in Gender column of first cell to `Male`, and then scroll the sheet down fast, and scroll up fast, you will see, the value inside the cell is `Female`, again 
```js
  // Commenting this event solves the problem ? The value of cell is already `commited` by `onChange` event
  // Update: It seems that this option being used to close the menu 
  onMenuClose={() => {
          return onCellChanged({
            ...cell,
            // The selectedValue is old value here why ?
            isOpen: !cell.isOpen,
            inputValue: undefined,
          });
        }}
```
Attaching [codesandbox](https://codesandbox.io/p/sandbox/cool-thunder-5hvcwq?file=%2Fsrc%2FApp.tsx%3A86%2C39) as a proof.

I have created `CustomDropDownCellTemplate.tsx` which is exact copy of dropdown cell implementation by ReactGrid. 

I have commented the `onMenuClose` event callback and everything works fine

Inside my `App.tsx`

```js
const getRows = (data: TData): Row[] => [
  headerRow,
  ...data.map<Row>((d, idx) => ({
       // Rest of the code
        //type: "dropdown",
        type: "rmcx",
        selectedValue: d.gender,
        inputValue: d.gender,
        isOpen: d.isOpen,
        values: [
          { label: "Male", value: "Male" },
          { label: "Female", value: "Female" },
        ],
      },
    ],
  })),
];


  const applyChanges = (changes: CellChange[], prevdata: TData): TData[] => {
    console.log("LLL", changes);

    changes.forEach((change) => {
    //  Rest of the code
      } else if (change.type === "rmcx") {
        rowData[fieldName] = change.newCell.selectedValue;
        rowData.isOpen = change.newCell.isOpen;
      }
    });

    return [...prevdata];
  };

```

**Comment by DVGY** [comment]
> Hi, your issues are not related to react-grid but your implementation. For example:
> 
> 1. performance issue: getRows function iterates all the people in O^2 although you can make it in O.
>    I suggest you to store the dropdown values in a Set.
> 2. people variable is overidden again and again when component is rendered. You need to change your implementation.
>    I suggest you to ask it on Stackoverflow but if you think there is a bug in React-Grid, please let me know..

It is strange that, it only happens for `dropdowncell` if I make this dropdown cell to `textcell` and keep on pressing down arrow, there is no lag. 

Update: 
You can confirm this by running `npm start` command for this repository then navigate to `src > test > TestGrid.tsx`, comment line 259 - 266 and you are good to press down arrow button, it should be alot smother than before.

**Comment by alonshmiel** [comment]
Can you please let me know if it works?

https://codesandbox.io/s/reactgrid-dropdown-example-hgtx4v

**Comment by DVGY** [comment]
> Can you please let me know if it works?
> 
> https://codesandbox.io/s/reactgrid-dropdown-example-hgtx4v

@alonshmiel **Works** !!! But **Does Not Works** in following use case

1. _If language cell is not empty initially_ [codesanbox](https://codesandbox.io/s/reactgrid-dropdown-example-forked-yxrtvp?file=/src/index.tsx)

It is happening because `onMenuClose` (Dropdowncell.tsx ) is resetting the value 

  
Replace this code 
```js
const getPeople = (): Person[] =>
  [...Array(300).keys()].map((index) => ({
    name: "Susie" + (index + 1),
    surname: "Quattro",
    surname2: "abc" + (index + 1),
    language: "react"
  }));
``` 
with this

```js
const languages = ["vue", "react", "angular"];

const getPeople = (): Person[] =>
  [...Array(100).keys()].map((index) => ({
    name: "Susie" + (index + 1),
    surname: "Quattro",
    surname2: "abc" + (index + 1),
    language: languages[Math.floor(Math.random() * languages.length)]
  }));

```
2. _Dropdown component is a not smoother to navigate with down arrow keys when there are more columns_

**Comment by alonshmiel** [comment]
I updated the code.
https://codesandbox.io/s/reactgrid-dropdown-example-hgtx4v?file=/src/index.tsx

Can you please add an example for #2?
I tried it and it looks good but please let me know if you have another case.
https://codesandbox.io/s/reactgrid-dropdown-example-forked-nlcqn3?file=/src/index.tsx

**Comment by DVGY** [comment]
Nice, the solution you gave is tricky 😄, but it works Thanks.  I think drop down component re renders again after selecting a value, and somehow it takes the stale state, or previous state. May be dropdown cell component need to be written again ? It is confusing, because I have to look into Implementation of `Dropdowncell.tsx`

@alonshmiel what are your thoughts about it ? 

For point 2 here is the video, I have used your example. So the problem happens only if you **long press down arrow key** see the cell focus seems to be stuck at row Susie78 or Susie181

https://github.com/silevis/reactgrid/assets/46158826/de5bfc29-a008-4503-97ce-8f1a405c7ee9

**Comment by alonshmiel** [comment]
Yes, I agree that it's not so intuitive :/
Regarding to the issue with arrow-down key, I see it but it's not critical in my opinion. Sorry..

**Comment by DVGY** [comment]
> Yes, I agree that it's not so intuitive :/ Regarding to the issue with arrow-down key, I see it but it's not critical in my opinion. Sorry..

That's okay, I know it is not critical.

**Comment by alonshmiel** [comment]
Hi @DVGY , please close this issue :)
