### ISSUE TITLE
fillHandle in vertical direction for dropdowntemplate 

### ISSUE THREAD

**Issue by DVGY** [silevis/reactgrid#178]
I think it a bug, fill handle for `dropdowncell.tsx` template is not working out of box, but works fine for rest of the cell template. 
I went through the source code and added this  ` selectedValue: selectedCell.selectedValue, `and fillhandle seems to work fine in down direction 

```js

    // reactgrid\src\lib\Behaviors\FillHandleBehavior.tsx
 
    const fillCellsWithPredictedValues = (
      selectedCells: Compatible<Cell>[],
      cellsToFill: Compatible<Cell>[]
    ): Compatible<Cell>[] => {
      const numbers = selectedCells.map((cell) => cell.value);
      const parameters = this.findRegressionFunction(
        numbers,
        Array.from({ length: numbers.length }, (_, index) => index + 1)
      );
      const areParametersNaNs = isNaN(parameters.a) && isNaN(parameters.b);
      return cellsToFill.map((cell, i) => {
        const x = this.calculateXForRegressionFunction(
          i + numbers.length + 1,
          parameters.a,
          parameters.b
        );
        const selectedCell = selectedCells[i % selectedCells.length];
        return {
          ...cell,
          // eslint-disable-next-line @typescript-eslint/ban-ts-comment
          // @ts-ignore

          selectedValue: selectedCell.selectedValue,
          text:
            areParametersNaNs || isKeyPressed
              ? selectedCell.text
              : x.toString(),
          groupId: selectedCell.groupId,
          value: areParametersNaNs || isKeyPressed ? selectedCell.value : x,
        };
      });
    };
```

Update I was thinking, a user of this library may create some XYZCellTemplate.tsx and may name value (key) as currentValue or some other key. Point is that, in docs if there is some standard for defining keys to make `fillCellsWithPredictedValues` work properly it will be great  😃 .

**Comment by alonshmiel** [comment]
Hi,
I am aware of this issue.

Can you please use a custom cell template instead?
I make it works here:

https://codesandbox.io/s/reactgrid-creating-new-cell-template-forked-58pj6p?file=/src/index.tsx

**Comment by DLowHP** [comment]
Hi! I think I've found a solution that works without violating Typescript rules, take a look at #203 and let me know if this works for you ;)
