### ISSUE TITLE
Is it possible to add validation to cell

### ISSUE THREAD

**Issue by DVGY** [silevis/reactgrid#179]
For example, a user enters a values -2 , it should become red and say, negative values are not allowed

**Comment by alonshmiel** [comment]
You can add 'validator' to the cell.
Cell: {
    validator?: (text: string) => boolean,
}

Here is an example:
https://codesandbox.io/s/suspicious-phoebe-cvd7vn?file=/src/index.tsx

You want to let user enter negative values and display an error message,
but you can prevent the user from entering negative values so you won't need error message.

If you want to prevent, you can create custom cell and handles the keydown + update (Please verify copy and paste removes the minus).

**Comment by DVGY** [comment]
Noice
