### ISSUE TITLE
How to make sure a dropdown cell template will work with RG internal fillHandle, cut, copy, paste

### ISSUE THREAD

**Issue by DVGY** [silevis/reactgrid#187]
I am trying to make fillHandle work here. How to make sure fillHandle works, copy, cut, paste also work?
[codesandbox](https://codesandbox.io/p/sandbox/downshift-pymcxc?file=%2Fsrc%2FFreeSoloDownShiftTemplate.tsx%3A49%2C29)

**Comment by DVGY** [comment]
Update on this, instead of using `selectedValue` as key I used `text` and it seems `fillHandle` is working, but the only problem is that the 
1. **values are not getting updated on the screen**. Is it a state issue ? I can see values updated inside `rows` variable
2. To copy a value I need to select the text and then it copies. For other cells inside like `TextCell`. It works even If I don't select text 
3. If I start navigating with arrow keys, I can press `Ctrl C` on `TextCell` and paste it. This does not work with `freesolo` or `dropdown` component.
4. It is very confusing where to put these events
```
  onCopy={(e) => {
        e.stopPropagation();
      }}
      onCut={(e) => e.stopPropagation()}
      onPaste={(e) => e.stopPropagation()}
```
I couldn't find what is use of this in docs 

[codesandbox](https://codesandbox.io/p/sandbox/downshift-forked-fdnyvg?file=%2Fsrc%2FFreeSoloDownShiftTemplate.tsx%3A76%2C46)

**Comment by DVGY** [comment]
@alonshmiel it would be really helpful (I know you are busy because of new born soul), if you could give some directions here.

**Comment by DLowHP** [comment]
Just as I've described in #178 I believe I've found solution for this which you can take a look at in the linked pull request (#203). I hope it helps, please let me know :)
