### ISSUE TITLE
Context Menu stays open even after remounting the component

### ISSUE THREAD

**Issue by michelangelo246** [silevis/reactgrid#188]
**Bug description and current behavior**
When the onContextMenu feature is enabled, if you click on a cell with the right button of the mouse, this will bring up the context menu options. If instead of selecting an option, you click on another cell, the context menu will close (as expected). 

But after that, if you unmount and remount the component (e.g. go to another page and then go back), the context state will be "restored" and a value for contextMenuPosition will be set, resulting in the ContextMenu component being rendered as open. 

**Expected behavior**
The state should be reset when the component re-mounts. When mounting the ReactGrid Component, it should not display the contextMenu component unless the user triggers it by right-clicking on a cell.

**Screenshots**
![image](https://github.com/silevis/reactgrid/assets/8918049/1a593081-57e6-49d5-a7e6-bf85b01e01a6)

**How to reproduce**
It can be reproduced in two ways:

1. Run the project. Go to the `enableHeaders` example. Right-click on a cell (on a single cell, not a multi-cell selection). With the context menu open, click on any other cell. Click on the Mount/Unmount button. 

2. Alternatively, the issue also exists on the docs page. Go to `https://reactgrid.com/docs/4.0/2-implementing-core-features/5-context-menu/` (v4.0 - Implementing core features > Context men). Click on the first "Show Live Preview" button. Right-click on a cell (on a single cell, not a multi-cell selection). With the context menu open, click on any other cell. Click on the "Preview" button. Go to any other page (e.g. navigate on the left-side menu). Go back to `(v4.0) Implementing core features > Context menu` on the left-side navigation menu. Click on the first "Show Live Preview" button again.

**Environment details**
 - Device:  Desktop
 - OS: Windows
 - Browser: Chrome

**Comment by michelangelo246** [comment]
The only workaround I've found for this issue is to set the `initialFocusLocation` prop. 

For example, if you change the `config` prop of the `ExtTestGrid` Component in the `/enableHeaders` case entry of `src\index.tsx` from `disabledInitialFocusLocationConfig` to `config`, it will work as expected.

**Comment by DLowHP** [comment]
Hi! I investigated this issue and I believe the "React-way" solution would be to set `key` property on ReactGrid component - see: [Resetting state with a key](https://react.dev/learn/preserving-and-resetting-state#option-2-resetting-state-with-a-key) on React docs. This tells React to create a state every time it appears on screen and remove when it disappears.

I'll close this issue, if you need further help please reopen it, or create a new one. Take care!

**Comment by michelangelo246** [comment]
@DLowHP  
>  the "React-way" solution would be to set key property on ReactGrid component

This was the first thing I tried when I first noticed the behavior. Though after realizing that the issue was still happening even after unmounting and remounting it, it was clear that this approach couldn't work.

I tried the approach both in my project as well as in the reactgrid project (it was still in my local stash):
<details><summary>Screenshot</summary>

![image](https://github.com/silevis/reactgrid/assets/8918049/6cec7c36-76f2-4448-a7c7-20efe32ea3f9)

</details>

The effect is the same as clicking the Mount/Unmount button twice.

[I must ask you](https://stackoverflow.com/a/21333938) to remove the `invalid` flag and reopen this issue, please, as it is a relevant one.

**Comment by DLowHP** [comment]
I feel dumb right now... Until yesterday, I would have said that setting the key directly on the ReactGrid component fixed the problem - that's why I wanted to ask why you put the key on the wrapper, but then I checked again and it seems that it doesn't work anymore, even when set on the RG component...

**Comment by DLowHP** [comment]
Okay, I came up with a possible solution - just before unmounting the ReactGrid component I reset context menu position in state - take a look:

```tsx
componentWillUnmount(): void {
    window.removeEventListener(
      "resize",
      this.eventHandlers.windowResizeHandler
    );
    this.state.scrollableElement?.removeEventListener(
      "scroll",
      this.eventHandlers.scrollHandler
    );
    this.setState({
      contextMenuPosition: { top: -1, left: -1 }
    });
  }
  ```

source: `src/lib/Components/ReactGrid.tsx@componentWillUnmount`.

Can you please tell me if this achieves the expected behavior?

**Comment by michelangelo246** [comment]
Thanks, @DLowHP, this seems to work indeed!

Can you open a PR with these changes?
