### ISSUE TITLE
Chevron cell is not working with the nonEditable:true prop in cell template

### ISSUE THREAD

**Issue by remotecraftr** [silevis/reactgrid#191]
My chevron cell is not working with the noneditable true. It does not open or close the cell.

**Comment by DLowHP** [comment]
Hi! I investigated this issue and it seems that setting `nonEditable` property to `true` on cell templates prevents ReactGrid from updating the state on cell's key/pointer events. This means that even though ChevronCell returns it's updated version with `isExpanded` property changed it isn't committed to RG state. My current workaround would be to create a custom cell template (based on our ChevronCell) and manage editability inside cell template or remove editing altogether.

**Comment by DLowHP** [comment]
I'm going to close this issue as it's inactive. If you still need help let us know.
