### ISSUE TITLE
Slow chevron cell toggle

### ISSUE THREAD

**Issue by ishantchauhan710** [silevis/reactgrid#197]
I have an array that contains over 5000 objects. When I use that array with react grid and scrolls through the web page, everything works smoothly. However, I am using chevron cell to group the rows and when I click on chevron button to toggle rows, there is a delay of 10 to 15 seconds. Is there any way to fix this issue?

**Comment by alonshmiel** [comment]
Hi, Can you please create a codesandbox?

**Comment by MichaelMatejko** [comment]
@ishantchauhan710 - we need something to reproduce the issue

**Comment by DLowHP** [comment]
I'm going to close this issue as it's inactive and we lack information. If you still need help with this let us know.
