### ISSUE TITLE
When editing a number cell  Ctrl-A will trigger the grid select all instead.

### ISSUE THREAD

**Issue by TikiTDO** [silevis/reactgrid#205]
**Describe the bug**
When editing a number cell, if you press Ctrl-A to select all text in the cell it will trigger the grid select all instead.

**Current behavior**

Pressing ctrl-a selects the entire grid

**Expected behavior**

Pressing ctrl-a should select the text in the cell being edited.

I was able to fix this in a custom template by checking for ctrl / meta key as below:

```tss
<input
  // ...
  onKeyDown={(e) => {
    if (
      inNumericKey(e.keyCode) ||
      isNavigationKey(e.keyCode) ||
      isAllowedOnNumberTypingKey(e.keyCode) ||
      e.ctrlKey ||
      e.metaKey
    )
      e.stopPropagation()
    if (
      (!inNumericKey(e.keyCode) &&
        !isNavigationKey(e.keyCode) &&
        !isAllowedOnNumberTypingKey(e.keyCode) &&
        !e.ctrlKey &&
        !e.metaKey) ||
      e.shiftKey
    )
      e.preventDefault()
  }}
/>
```

Using [this code](https://github.com/silevis/reactgrid/blob/4c36d9ed6d069f66f9afd756ee8a55e142ad344b/src/lib/CellTemplates/NumberCellTemplate.tsx#L96) as the basis.

**Package Versgion**

"@silevis/reactgrid@^4.0.5"

**Comment by DLowHP** [comment]
I investigated the issue and found that this behavior exists in all number based cell templates. The linked PR should fix that.
