### ISSUE TITLE
Pasting multiple rows does not change the rows count

### ISSUE THREAD

**Issue by webshared** [silevis/reactgrid#206]
Reactgrid is a great component to use. But this issue is critical for many use cases. 

Is there a workaround for this?

**Comment by MichaelMatejko** [comment]
I agree, but the row and column count is controlled by the parent component. 

To achieve the expected behavior the user should process the paste event by himself. To achieve this, he needs to understand at least which cell is currently focused.

**Comment by DLowHP** [comment]
This won't be fixed for now, but we'll take this into consideration in the next release. If you need anything else feel free to reach out to us c;
