### ISSUE TITLE
Editing a cell causes the app to crash with `TypeError: n is undefined`

### ISSUE THREAD

**Issue by baswelsh** [silevis/reactgrid#208]
**Describe the bug**
From a fresh page reload, clicking in a cell a single time and then changing the value causes a `TypeError: n is undefined` error.  To recreate:

1. Navigate to the embedded Sandbox at the bottom of https://reactgrid.com/docs/4.0/2-implementing-core-features/1-handling-changes/.
2. Click in the cell with contents "Thomas"
3. Type "Other" and press enter
4. TypeError: n is undefined

Note that I don't believe this behavior existed ~1 week ago.

**Expected behavior**
No error thrown.  Oddly enough, the behavior is correct if you click in the cell twice before changing its value.  Also after the first time, editing any cell by clicking once and pressing Enter causes no error.  It is just the first edit.

**Screenshots or gifs**
<img width="1170" alt="image" src="https://github.com/silevis/reactgrid/assets/74797106/32529ec1-24a2-416e-9bc6-1235cc3a79ad">

**Your environment details**
 - Device:  Macbook Pro (M2)
 - OS: macOS
 - Browser: firefox and safari

Thanks for the help!

**Comment by baswelsh** [comment]
I believe this might be related.  The following is now logged to the console on cell update.  Did a dependency possibly update recently? 
<img width="530" alt="image" src="https://github.com/silevis/reactgrid/assets/74797106/03a23af5-c042-482f-a2a0-e5e1aa3c46c6">

**Comment by DLowHP** [comment]
This issue seems to be purely related to this docs' sandbox as [updating the versions](https://codesandbox.io/s/reactgrid-handling-changes-forked-y3r2sy) fixes the issue. 
I don't plan on changing the docs for now as they will still need updating after publishing the develop's changes anyway.
