### ISSUE TITLE
Cell Editor not staying overlaid over the cell being edited when scrolled

### ISSUE THREAD

**Issue by ashleych** [silevis/reactgrid#209]
**Describe the bug**
When I click on a cell to enter edit mode, and then scroll down on the main window, the Cell Editor appears to be positioned with 'absolute' values, which means that it appears that the cell editor is floating rather than being overlaid on the cell being edited. 

I see this happens with the Examples on the website as well - [Examples(https://reactgrid.com/examples)]

**Current behavior**
A clear and concise description of what you current see.

**Expected behavior**
One expects that the positioning will always remain over the cell being edited

**Screenshots or gifs**
Added screenshot
![positioning](https://github.com/silevis/reactgrid/assets/3990319/94f22540-529b-462e-8363-7fa3d73e955c)

**Your environment details**
 - Browser  chrome Version 115.0.5790.170 
  ]

**Comment by MichaelMatejko** [comment]
Hi [ashleych](https://github.com/ashleych)
This is a feature not a bug. It is needed, if you want to scroll the grid to see other values which you want to compare.
Same behavior as in Google Spreadsheet. 
Best
Michael
