### ISSUE TITLE
change min column width to a custom value, I actually need 30px

### ISSUE THREAD

**Issue by flaviodifraia** [silevis/reactgrid#210]
There is no way to go below 40px for column width apparently

What can I edit to get it to a custom value?

Thanks

**Comment by MichaelMatejko** [comment]
It's acutally a hardcoded value. @DLowHP what do you think about a public prop: ``minCellWidth`` ?

**Comment by DLowHP** [comment]
That's what I planned on doing. I'm going to try it tomorrow ;)

**Comment by thadeubrito** [comment]
Is it required because of `resizable: true` in the columns? 
Another question, is not possible to limit the size based in the content inside the header cell?
There is no way to set width in percentage?

**Comment by DLowHP** [comment]
Yes, min column width is used to limit the width column can be resized down to.
It might be possible but I think it might be a bit difficult to implement with current implementation.
No, even if we ignore the fact that we internally use pixels to perform various calculations percentage sizes would be calculated based on "real" (whole, the same as with virtualization disabled) size of ReactGrid which is in turn dependent on its content size so it would most likely cause problems.

**Comment by DLowHP** [comment]
I made a PR #214 that introduces prop that makes min column width customizable by `minColumnWidth` property.
