### ISSUE TITLE
v4.1.0 import issue

### ISSUE THREAD

**Issue by morgan-bp** [silevis/reactgrid#217]
After installing the latest version from npm, my app can no longer detect the package.

<img width="878" alt="image" src="https://github.com/silevis/reactgrid/assets/122408333/e3dd9edf-c011-482c-a480-9e6ecdb4e2c1">

It seems that the built module was distributed within the source files and adding importing with a `/dist` appended `@silevis/reactgrid/dist` fixes the problem.

<img width="591" alt="image" src="https://github.com/silevis/reactgrid/assets/122408333/a01a9c86-efb7-488f-b86b-48bdec07b5f5">

This is a still a problem and should be fixed as it is a breaks existing code and adding a `/dist` to the package name is not intuitive.

**Comment by JiaFei1991** [comment]
I have to manually revert to 4.0.5 for my project to work, but @morgan-bp 's solution is the way to go right now, please fix soon

**Comment by jaysonmulwa** [comment]
Fixed the issue by installing a precise previous version of the package 4.0.4 with  `yarn add @silevis/reactgrid@4.0.4`

**Comment by DLowHP** [comment]
Sorry, I had some trouble with npm authorization on our publish pipeline and while making changes to its config I forgot to set `workingDir`. A patched version `4.1.1` has been published, it should not require referencing `dist` directory anymore.
