### ISSUE TITLE
Source Code for Examples

### ISSUE THREAD

**Issue by TarunGarapati** [silevis/reactgrid#218]
Can someone provide the source code links for 5 example grids present in [https://reactgrid.com/examples.

**Comment by artt** [comment]
I agree that the doc could be improved. Here's what I found that might be useful:

* [Source code for the website](https://github.com/silevis/reactgrid-website/tree/gh-pages-dev/src/samples/samplesSrc)
* [A repo called `reactgrid-samples`](https://github.com/silevis/reactgrid-samples)
