### ISSUE TITLE
Fixed cell position on scroll while in edit mode

### ISSUE THREAD

**Issue by tytevaipie** [silevis/reactgrid#221]
**Describe the bug**
When editing mode is invoked for a cell and scrolling is performed simultaneously, cell remains in a fixed position.

**Expected behavior**
Editable cell position should remain relative to the grid.

**Screenshots or gifs**
![reactgrid_bug](https://github.com/silevis/reactgrid/assets/143584664/3ccd039f-a21e-45e7-b328-3c979c5703d2)

**Your environment details**
 - Device:  Desktop
 - Browser: Chrome, Firefox, Edge

**Comment by DLowHP** [comment]
This is the expected behavior. Do you think it should be locked to grid container rather than body?

**Comment by pawaningale93** [comment]
Yes @DLowHP It should be locked as it is looking ugly. Let us know if any workaround is there for this.

**Comment by pawaningale93** [comment]
> This is the expected behavior. Do you think it should be locked to grid container rather than body?
Yes @DLowHP It should be locked to grid container as it is looking ugly floating textbox. Let us know if any workaround is there for this.

**Comment by tytevaipie** [comment]
> This is the expected behavior. Do you think it should be locked to grid container rather than body?

Yes, the editable cell should stay within the grid component as it makes no sense for it to float over the other unrelated components on scroll.

**Comment by DLowHP** [comment]
I had to reopen this issue as the solution I pushed does not work on sticky/frozen cells. I totally forgot to check it before merging the PR - my bad, sorry! Unfortunately after spending significant amount of time searching for a better solution I must sadly say that this won't be fixed in the current RG version as it would require too much changes potentially introducing new issues.
Nevertheless I think this could be introduced in the upcoming v5 🤔

**Comment by qiufeihong2018** [comment]
I think both scenarios can exist, and it is recommended that users customize them through configuration.
1. Cells do not scroll along with the page, have been in the window, do not disappear, allowing users to focus on editing.
2. As the cell scrolls through the page, it can not cover other modules, which can make the component complete

**Comment by lamdev03** [comment]
Thank you, Bro
Can I combine columns and lines and display excel like input cells to be
more beautiful?

Vào Th 5, 7 thg 12, 2023 vào lúc 14:24 大卫 ***@***.***> đã
viết:

**Comment by lamntph28897** [comment]
Is there any way to select multiple columns and rows then press merge it?

Vào Th 5, 7 thg 12, 2023 vào lúc 14:44 Thần Tài Đến ***@***.***>
đã viết:

**Comment by qiufeihong2018** [comment]
@lamntph28897 This already seems to be an issue https://github.com/silevis/reactgrid/issues/88

**Comment by merabtenei** [comment]
@DLowHP That's unfortunate, We really thought we finally found the perfect library for our project but everyone said no to this and there's no easy way to fix this. Everyone is used to Cells staying at their respective positions as in this library : https://adazzle.github.io/react-data-grid/#/common-features

**Comment by MichaelMatejko** [comment]
in v5 this feature will be removed.
