### ISSUE TITLE
Wide merged cell gets removed before it goes out of view

### ISSUE THREAD

**Issue by artt** [silevis/reactgrid#222]
**Describe the bug**
When a cell with `span` > 1 is wide enough, the cell gets removed even before it goes out of view. This is especially noticeable when it's a cell with background (e.g. header cell).

**Current behavior**
The cell gets removed before it goes out of view.

**Expected behavior**
The cell remains visible until the entire cell goes out of view.

**Screenshots or gifs**

https://github.com/silevis/reactgrid/assets/1711188/14fb4da2-47f5-472a-9a78-4ab7179302b6

**Your environment details**
 - Device:  Desktop
 - OS: macOS
 - Browser: Problem in Chrome, Firefox, and Safari

**Comment by DLowHP** [comment]
Related to this comment: https://github.com/silevis/reactgrid/issues/116#issuecomment-1614453274. I found a [workaround](https://codesandbox.io/s/reactgrid-liquidity-planner-forked-qjt2yf) for it, you can take a look at it and try to apply it to your case.
If you need anything else, let me know. Take care!
