### ISSUE TITLE
Column grouping possible?

### ISSUE THREAD

**Issue by Ravivishwa** [silevis/reactgrid#223]
Hello, appreciate the great effort,
I have one implementation question, is it possible to achieve column grouping? If yes can you provide me a minor example
Something like this
![image](https://github.com/silevis/reactgrid/assets/19967683/028724b9-9f91-4ecf-98bd-964797cfbc2e)

Thanks in advance

**Comment by artt** [comment]
You can have two header rows, with the first having `colspan` of however many cells you want. See [here](https://reactgrid.com/docs/4.0/2-implementing-core-features/9e-cell-span/).

There's still a bug where if you enable column selection then nothing happens when you click on the second header row. Still trying to figure that out.

**Comment by bayaroch-um** [comment]
colspan buggy when there is alot of columns. its get white on scrolling vertical. made solution give width on first column that overriding other blank columns.

**Comment by DLowHP** [comment]
Yes, colspan would be the solution to this, but as it's stated in the docs it's currently an experimental feature. I suppose we'll add this with full support in the upcoming 5th version. You can follow the developement [here](https://github.com/silevis/reactgrid/tree/v5-dev). Feedback and help welcome!
Hope you understand, take care!

**Comment by DLowHP** [comment]
Related issue: #88

**Comment by lamdev03** [comment]
When is the new version expected to be released? Does it last? I'm looking forward to it.

**Comment by DLowHP** [comment]
We are planning to release the first v5 iteration in the [Q1 2024](https://github.com/silevis/reactgrid/issues/88#issuecomment-1801405403).

**Comment by MichaelMatejko** [comment]
will be available in v5
