### ISSUE TITLE
Request: onClick callback

### ISSUE THREAD

**Issue by artt** [silevis/reactgrid#225]
I see there's `onFocusLocationChanged` callback, but it doesn't fire when a row or a column is clicked (with `enableRowSelection` enabled). It would be nice to have that.

Trying to use the workaround suggested [here](https://github.com/silevis/reactgrid/issues/222#issuecomment-1707814456) but would like to have columns of the "merged cells" selected when the cell is clicked as well.

**Comment by DLowHP** [comment]
If I understood correctly, what you're trying to achieve won't currently work as cell span is an experimental feature and a lot of functionalities don't work correctly yet. I suppose this will only be fixed in the upcoming v.5 release. Sorry!

**Comment by artt** [comment]
Yeah I learned how to implement `chevron` cells and seems like we have to go quite low just to get `onClick` event. Just wish common use cases like these are built in.
