### ISSUE TITLE
export 'useInsertionEffect' (imported as 'e') was not found in 'react'

### ISSUE THREAD

**Issue by lcoalves** [silevis/reactgrid#227]
**Describe the bug**
After updating to the version 4.1.1 we are experiencing the error below.

![image](https://github.com/silevis/reactgrid/assets/46606051/cf18fc1a-6e9a-4af8-a787-b132091ec265)

**Current behavior**
ERROR in ./node_modules/@silevis/reactgrid/core/handleStateUpdate-13a9c5a8.js 2995:9-29
export 'useInsertionEffect' (imported as 'e') was not found in 'react' (possible exports: Children, Component, Fragment, Profiler, PureComponent, StrictMode, Suspense, __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, cloneElement, createContext, createElement, createFactory, createRef, forwardRef, isValidElement, lazy, memo, useCallback, useContext, useDebugValue, useEffect, useImperativeHandle, useLayoutEffect, useMemo, useReducer, useRef, useState, version)

ERROR in ./node_modules/@silevis/reactgrid/core/handleStateUpdate-13a9c5a8.js 2995:33-53
export 'useInsertionEffect' (imported as 'e') was not found in 'react' (possible exports: Children, Component, Fragment, Profiler, PureComponent, StrictMode, Suspense, __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED, cloneElement, createContext, createElement, createFactory, createRef, forwardRef, isValidElement, lazy, memo, useCallback, useContext, useDebugValue, useEffect, useImperativeHandle, useLayoutEffect, useMemo, useReducer, useRef, useState, version)

webpack compiled with 2 errors and 1 warning
No issues found.

**Expected behavior**
The SPA application not start.

**Screenshots or gifs**
![image](https://github.com/silevis/reactgrid/assets/46606051/f63f2d37-02d3-4af1-9a19-9c6df36bf993)

**Your environment details**
 - Device:  Desktop
 - SO: Ubuntu 20.04
 - Browse: Chrome

**Comment by DLowHP** [comment]
Which React version do you have installed?

**Comment by lcoalves** [comment]
React 17 @DLowHP 

![image](https://github.com/silevis/reactgrid/assets/46606051/7a9fe924-fc71-475a-b0eb-d44125460b7d)

**Comment by DLowHP** [comment]
I believe `useInsertionEffect` is a React 18 addition. Try updating and let me know how it went.

**Comment by lcoalves** [comment]
@DLowHP it worked. Thank you.

![image](https://github.com/silevis/reactgrid/assets/46606051/1a0c8f43-3266-4033-b4ed-8911da49f741)

![image](https://github.com/silevis/reactgrid/assets/46606051/d3546ee0-a05f-4a84-bb48-b2ab06163db2)

I suggest updating the documentation to say that the library only works from react 18 onwards.

**Comment by ayankapadiya** [comment]
Hello, I am using React version "17.0.2" which is compatible with my application. I have integrated React Grid into my project, but getting errors like this local and during the publish,

![image](https://github.com/silevis/reactgrid/assets/145652510/f7872e83-898b-4ed5-a6f2-6d967b640fd9)

I want to use React Grid in my current React version. Don't want to upgrade latest. Can you please help me with this?

**Comment by DLowHP** [comment]
Hi! It seems that while building for React 18 the compiler uses the new hook `useInsertionEffect` somewhere internally. I'll try to find a workaround for this, and for now you can downgrade to **ReactGrid v.4.0.5**.

**Comment by ayankapadiya** [comment]
Okay, thanks for the quick reply. 
For, now I will downgrade to React Grid v.4.0.5. And yes, please resolve this issue for me for @silevis React grid latest version. Thanks in advance.

**Comment by ayankapadiya** [comment]
Hello Daniel Fidor,

I am using version 4.0.5 and it is working fine locally. But, I am trying to publish it, it is giving an error like "Attempted import error: 'useInsertionEffect' is not exported from 'react' (imported as 'e').". 

Can you please help me with this?

Thanks

**Comment by ayankapadiya** [comment]
Hello, 

Getting the same error in the ReactGrid v.4.0.5. Not able to publish the code.

**Comment by DLowHP** [comment]
Hi! What do you mean by publish?

**Comment by ayankapadiya** [comment]
I used this grid on my page and when I publish this code on the GitLab server, this error comes.

**Comment by DLowHP** [comment]
Could you provide a sandbox or something similar so that I can try it myself?

**Comment by ayankapadiya** [comment]
This 'useInsertionEffect' was available in React v4.0.5 or it was just added in new React v4.1.1 version?

**Comment by ayankapadiya** [comment]
If it did not exist in the previous version then why I am receiving this error during deployment?

**Comment by DLowHP** [comment]
I believe it has been added from v4.1.0 when we added React 18 support. I don't know why it comes up in your case, I would need more info to try this myself.

**Comment by ayankapadiya** [comment]
I am using React v17.0.2 and Silevis v4.0.5.

Can you please update React v4.0.5 in your project and try this? Also, try to deploy this on some staging or live URL, then you get the error.

**Comment by DLowHP** [comment]
Hi, I wasn't able to reproduce this issue myself. I deployed [this sandbox](https://codesandbox.io/s/reactgrid-handling-changes-forked-y3r2sy) that uses ReactGrid@4.0.5 and React@17.0.2 on [Vercel](https://csb-y3r2sy.vercel.app/) without any issue. Could you provide more info?

**Comment by ayankapadiya** [comment]
Getting the same error with ReactGrid@4.0.5 and react@17.0.2

**Comment by ayankapadiya** [comment]
I have implemented a react grid in my project with dynamic data. I am using react@v17.0.2 and selvis@4.0.5. 

when I was trying to deploy this project on the Git repository than got this error. As per the previous comment, I have tried React Grid's latest version but getting the same error during deployment on git repository.

**Comment by DLowHP** [comment]
Sorry, I don't know how else to help you. I tried the same versions you provided and deployed the project without experiencing any problem - maybe this is an issue with your deployment environment/config?

**Comment by subhamayd2** [comment]
This is still an issue for ReactGrid@4.1.3 and React@17. Is there any workaround for this without upgrading React version?
