### ISSUE TITLE
Latest version of Chrome (117.0.5938.62) broke stickyLeftColumns

### ISSUE THREAD

**Issue by artt** [silevis/reactgrid#229]
**Describe the bug**
Just upgraded to the latest version of Chrome and the sticky left columns are overlaid by the scrolling cells on the right. See https://reactgrid.com/examples/ as an example. This doesn't happen in
* Safari (16.5.2 (18615.2.9.11.10))
* Edge (116.0.1938.81)
* Firefox (117.0)

**Expected behavior**
The sticky columns should be on top.

**Screenshots or gifs**
![image](https://github.com/silevis/reactgrid/assets/1711188/5068aa93-0502-4e57-a366-4a68fb74cf9d)

**Your environment details**
 - Device:  Desktop
 - OS: macOS
 - Browser: Chrome

------------

**Current workaround**: https://github.com/silevis/reactgrid/issues/229#issuecomment-1729178564

**Comment by philip-lk** [comment]
I have noticed the exact same thing.

**Comment by philip-lk** [comment]
This issue also occurs with sticky headers. Is there a work around or a fix?

**Comment by DLowHP** [comment]
Hmm, I think it might have to do with the order property. I'm not sure what _exactly_ has changed in the latest version of Google Chrome that would mess this up though. The easiest workaround would probably be to supply `z-index` values to the appropriate `rg-pane-*` classes.

**Comment by mo-moradi-cap** [comment]
Not a final solution but works for now!!
```
  .rg-pane.rg-pane-left {
    z-index: 1;
  }

  .rg-pane.rg-pane-top {
    z-index: 2 !important;
  }

  .rg-pane.rg-pane-right.rg-pane-top {
    z-index: 3 !important;
  }

  .rg-pane.rg-pane-left.rg-pane-top {
    z-index: 3 !important;
  }
```
