### ISSUE TITLE
Reading value from a cell and Uneditable Grid

### ISSUE THREAD

**Issue by TarunGarapati** [silevis/reactgrid#230]
How to read the value of a dropdowncell or any textcell when I pass the rows to any functional component as props?
Also How do I make the selected columns of the grid or the entire grid uneditable?

**Comment by TarunGarapati** [comment]
Can someone provide the code snippet for the above scenarios please?

**Comment by DLowHP** [comment]
What do you mean by reading a prop provided to functional component? You can use `onCellChanged` functions to react to changes and update your state accordingly.
Depends on the use case but you could "fork" TextCellTemplate and disable edit mode internally.

**Comment by TarunGarapati** [comment]
Hi @DLowHP ,
I managed to read the values of dropdowncell and textcell after passing the Grid Data to another functional component.
Can you send me the code snippet to disable edit mode for a particular Column or the entire Grid?
Also I'm facing issue with fill handle even though I enabled it in my ReactGrid component. Any suggestions?

**Comment by alonshmiel** [comment]
Hi,
I am not sure your issues but:
In order to disable a cell, you can use: nonEditable for every cell.
If you want your whole grid to disable "edit mode", you can set is true for every cell.

If you want a specific column to be disabled, you can find the the column id and then get all of the cells with this column id and set nonEditable to true.

**Comment by DLowHP** [comment]
Hi @TarunGarapati! Alon is right here - you can use nonEditable to disable edit mode for a part of the grid. Take a look at this [example sandbox](https://codesandbox.io/s/reactgrid-disable-column-edit-4hmdgh?file=/src/index.tsx).
Unfortunately I don't understand your fill handle issue, could you provide more info?
