### ISSUE TITLE
Could you allow a percentage character '%' to be entered in NumberCell

### ISSUE THREAD

**Issue by pythactuary** [silevis/reactgrid#231]
**Describe the bug**
Currently only numbers, commas, periods and minus characters are allowed to be entered in a NumberCell. It would be useful to be able to enter a percentage character as well, so I can write '5%' rather than 0.05.

**Current behavior**
Entering a '%' character in a NumberCell is not allowed.

**Expected behavior**
Entering a '%' character in a NumberCell is allowed (possibly could be restricted to the final character). The percentage is parsed to a number (i.e 5% => 0.05), however it is then formatted and displayed as per the format specified for the cell.

**Your environment details**
 - Device:  Desktop
 - OS: Ubuntu
 - Browser: Chrome

**Comment by DLowHP** [comment]
You can "fork" NumberCellTemplate and implement it yourself ;) 

Something like this should work (untested, I wrote it in the Github comment editor 😅): 

```ts
onChange={e => onCellChanged(this.getCompatibleCell({ 
  ...cell, 
  value: e.currentTarget.value.match(/\d+%/g) ? 
    Number.parseFloat(e.currentTarget.value) * 0.01 : parseFloat(e.currentTarget.value.replace(/,/g, '.')) 
}), false)}
```

**Comment by pythactuary** [comment]
Thanks, I created a new custom cell template which has worked well

**Comment by DLowHP** [comment]
Cool! If you'll need anything else let us know - for example by creating another issue ;)
