### ISSUE TITLE
Number Cells Not working?

### ISSUE THREAD

**Issue by boomgetchopped** [silevis/reactgrid#232]
Hello if I use text cells the grid has no problem keeping track of user changes to cells. But for number cells, whenever I exit a cell, the typed value is not retained.  Example:
https://codesandbox.io/s/reactgrid-handling-changes-forked-swl3qj

Enter into a cell in the "My Number" column, type a number. Then leave. The cell is blanked out after leaving.

**Comment by purav-parekh** [comment]
Were you able to solve this issue? How did you do it?
