### ISSUE TITLE
Sticky columns broken in small screen

### ISSUE THREAD

**Issue by thuanhoang97** [silevis/reactgrid#233]
**Describe the bug**
When we are on a small screen or resize the screen, sticky columns break. I forked examples from the docs and adjusted only the width and the number of sticky columns. On a large screen, it displays as expected, but after resizing to a small screen, it no longer appears sticky.

[Forked example](https://codesandbox.io/s/reactgrid-liquidity-planner-forked-ylv54d?file=/src/getColumns.ts)

**Current behavior**
Columns does not remain sticky  a small screen.

**Expected behavior**
Columns should remain sticky even on a small screen.

**Your environment details**
 - Device:  Desktop
 - OS: macOS
 - Browser: Chrome (117.0.5938.92)

https://github.com/silevis/reactgrid/assets/38289417/c751f38e-4b58-4ff4-8ad1-b98e01f21210

**Comment by DLowHP** [comment]
I believe this has to do with "sticky breakpoints". Take a look at: [Responsive sticky | ReactGrid](https://reactgrid.com/docs/4.0/2-implementing-core-features/9d-responsive-sticky/).

**Comment by thuanhoang97** [comment]
I missed it in the docs. It works as expected. Thank you for your help.

**Comment by DLowHP** [comment]
No worries, I'm here to help ;D
