### ISSUE TITLE
[Feature request] Custom component for the context menu

### ISSUE THREAD

**Issue by tytevaipie** [silevis/reactgrid#234]
**Expected behavior**
Would it be possible to implement an option to provide a custom react component for onContextMenu handler which would then be rendered when contextual menu is invoked instead of the default menu?

**Comment by DLowHP** [comment]
I don't think a custom component for the menu is possible, but you can take a look at the documentation for [custom menu options](https://reactgrid.com/docs/4.0/2-implementing-core-features/5-context-menu/) 😀

**Comment by qiufeihong2018** [comment]
Why is custom component of menu not possible?

**Comment by DLowHP** [comment]
Because such option was not (yet? might be added in the upcoming v5) implemented in the current RG version 😅

**Comment by MichaelMatejko** [comment]
context menu will be removed from v5. User needs to implement his own.
