### ISSUE TITLE
CTRL multiselect does not Copy correctly

### ISSUE THREAD

**Issue by jack-van-holland** [silevis/reactgrid#239]
**Describe the bug**
When using multiselect by holding ctrl and clicking many cells, the cells appear selected, but are not copied. By contrast just holding the mouse or shift select contiguous ranges and copies correctly. 

**Current behavior**
Only the last selected cell is actually included in the copy when selecting multiple by holding ctrl. 

**Expected behavior**
All selected cells should be included in the copy. 

**Screenshots or gifs**
![MultiSelect Copy bug](https://github.com/silevis/reactgrid/assets/60764738/ab38e5e7-5bd3-416c-8986-10e16228e284)

**Your environment details**
 - Device: Desktop
 - OS: Windows
 - Browser : Firefox, Edge, Chrome

**Comment by DLowHP** [comment]
Hi! This behavior is intended and resembles MS Excel/G Sheets behavior.
