### ISSUE TITLE
Cannot use enableRangeSelection on a grid that uses custom cell templates.

### ISSUE THREAD

**Issue by SofiaVega** [silevis/reactgrid#240]
Is there a way to enable range selection when using custom cell templates? Do I need to change anything in my template definition? I added enableRangeSelection={true} when I create a react grid component but it doesn't let me select more than one cell at the time. Wondering if I'm missing something in my custom template.

**Comment by DLowHP** [comment]
Hi, could you provide a sandbox? Range selection should work without problems on custom cells.
