### ISSUE TITLE
exposing isMulti for enabling multiple selection dropdowns

### ISSUE THREAD

**Issue by mrgianlu** [silevis/reactgrid#241]
**Describe the bug**
Expose isMulti of React Select for enabling multi-select dropdown

**Current behavior**
Option not exposed

**Expected behavior**
This is a cool feature, quite easy to implement but still very useful.

**Screenshots or gifs**
N/A

**Comment by DLowHP** [comment]
Hi! You can [create your own cell template](https://reactgrid.com/docs/4.0/5-create-your-own-cell-template/) and implement such functionality yourself ;) Of course you don't have to start from scratch, you can just "fork" the [DropdownCell template](https://github.com/silevis/reactgrid/blob/develop/src/lib/CellTemplates/DropdownCellTemplate.tsx).
