### ISSUE TITLE
First frozen column might be broken

### ISSUE THREAD

**Issue by aaramians** [silevis/reactgrid#243]
Something maybe wrong with frozen first columns.
![image](https://github.com/silevis/reactgrid/assets/17715420/fb3f73ce-905a-464b-b404-a21d985b335b)

Chrome:
Version 117.0.5938.134 (Official Build) (64-bit)

its looks right in FireFox, maybe something got updated on chrome

**Comment by jack-van-holland** [comment]
See #229

**Comment by qiufeihong2018** [comment]
Isn't this solved? Why not turn it off?

**Comment by DLowHP** [comment]
Resolved in [v4.1.2](https://github.com/silevis/reactgrid/releases/tag/v4.1.2) 😁
