### ISSUE TITLE
Responsive Width

### ISSUE THREAD

**Issue by boomgetchopped** [silevis/reactgrid#244]
**Describe the bug**
Not a bug, but a nice feature to have would be to set a column to responsive width so that it takes up remainder space, instead of hardcoding width of every column.

**Current behavior**
Currently every column must be fixed width.

**Expected behavior**
To allow setting width of a column to 'flex-grow' for example, so it's width takes up remainder width of container.

**Comment by DLowHP** [comment]
The fixed width is there because of virtualization but we're planning to handle different values (such as "max-content", "flex factor" - the "fr" unit, etc.) in the upcoming v5 version ;)

**Comment by MichaelMatejko** [comment]
moved to v5
