### ISSUE TITLE
Bug: broken link in the docs

### ISSUE THREAD

**Issue by IdoBouskila** [silevis/reactgrid#246]
**Describe the bug**
The bug is related to a broken link on the following page: https://reactgrid.com/docs/4.0/4-cell-templates/5-ChevronCell/.

**Current behavior**
On the page mentioned above, there is a link that says  "Open ChevronCell implementation on [GitHub](https://github.com/silevis/reactgrid/blob/v4.0.2/src/lib/CellTemplates/ChevronCellTemplate.tsx)." However, when clicking this link, it leads to a 404 - page not found error on GitHub.

**Expected behavior**
I expected the link to take me to the GitHub repository or page containing the implementation details for the **ChevronCell** component, providing access to the source code or related information.

**Screenshots or gifs**
N/A

**Your environment details**
    Device: Desktop
    OS: Windows 10
    Browser: Chrome

**Comment by IdoBouskila** [comment]
I fixed that in PR silevis/reactgrid-website#23.
Please review and merge if everything looks good.
Thank you!

**Comment by DLowHP** [comment]
I've added a comment in your PR, please take a look at it.

**Comment by DLowHP** [comment]
PR merged.
