### ISSUE TITLE
Is example code for Budget Planner available? 

### ISSUE THREAD

**Issue by anandkumarpatel** [silevis/reactgrid#257]
I want to implement column folding and wanted to look at the source code for the example: [Budget planner](https://reactgrid.com/examples/?example=budget-planner). Is it available anywhere?

**Comment by DLowHP** [comment]
Yes, take a look at [BudgetPlanner sample source](https://github.com/silevis/reactgrid-website/tree/gh-pages-dev/src/samples/samplesSrc/bp) on reactgrid-website repo.

**Comment by anandkumarpatel** [comment]
Amazing thanks!
