### ISSUE TITLE
Is there example code to externally handle cell's focus change?

### ISSUE THREAD

**Issue by mayank-verma-stv** [silevis/reactgrid#258]
I am looking a solution for handling my cell changes externally, because i need to change cell's location to a new cell when i add new cell.

**Comment by DLowHP** [comment]
Take a look at [Focus management docs](https://reactgrid.com/docs/4.0/2-implementing-core-features/7-managing-focus/). You can use `focusLocation` property to manage the focus yourself.

**Comment by mayank-verma-stv** [comment]
can't find solution in documents @DLowHP

**Comment by DLowHP** [comment]
Unfortunately I think we don't have example code for this use case. I suppose you'd have to manage the changes externally by implementing mechanisms such as moving the focus using keyboard arrows, changing the location on click etc. yourself.
