### ISSUE TITLE
When will v4.1.2 be released?

### ISSUE THREAD

**Issue by qiufeihong2018** [silevis/reactgrid#259]
**Describe the bug**

**Current behavior**
A clear and concise description of what you current see.

**Expected behavior**

**Screenshots or gifs**

**Your environment details**
 - Device:  [e.g. mobile/desktop]

**Comment by DLowHP** [comment]
I'll have to review PR's with the PO (probably today) and I think I could publish a release today or on Thursday...

**Comment by DLowHP** [comment]
The v4.1.2 has been released: https://www.npmjs.com/package/@silevis/reactgrid

**Comment by qiufeihong2018** [comment]
Thanks!
