### ISSUE TITLE
Sticky Row is overlapped by scrolling content

### ISSUE THREAD

**Issue by boomgetchopped** [silevis/reactgrid#265]
You can see that while scrolling, the cells content will be displayed on top of the header. The header stays in place, but it gets covered up by the scrolling content
![image](https://github.com/silevis/reactgrid/assets/5420943/50167d0e-7576-4c02-b6f0-d0b26f59d2a3)

**Comment by DLowHP** [comment]
Hi! Which version of ReactGrid do you have? This was caused by bug in Chrome starting from v117 (see #229) but has been fixed in the [v4.1.2 version of ReactGrid](https://github.com/silevis/reactgrid/releases/tag/v4.1.2).

**Comment by boomgetchopped** [comment]
Hello, thanks, after upgrading to the latest version this issue is now resolved.
