### ISSUE TITLE
handle focus change externally

### ISSUE THREAD

**Issue by mayank-verma-stv** [silevis/reactgrid#266]
Hey folks, I need to add a functionality, Where I'm supposed to completely handle cell on my own, because I'll have an add cell button and when I click on it, I'll need to move focus to a particular cell, although I have added logic for add cell button , just suggest me to handle focus changes externally.

**Comment by DLowHP** [comment]
Hi! You can use the [`focusLocation` property](https://reactgrid.com/docs/4.0/2-implementing-core-features/7-managing-focus/) to handle it manually.
