### ISSUE TITLE
Is there any way to highlight active row when mouse hovering

### ISSUE THREAD

**Issue by bayaroch-um** [silevis/reactgrid#267]
i know i have data-row-idx data attribute but i dont have solution to dynamicly apply each same row cells background style. is there any easy way to do it ?. Like add enableRowSelection props. enableHoverRow etc

**Comment by DLowHP** [comment]
Hi! Take a look at how it's done in [the official example](https://github.com/silevis/reactgrid-website/blob/9197ee0502269c4a72e675b1c5d8f3664ae86151/src/samples/samplesSrc/workhoursSample/WorkhoursGrid.tsx#L73-L76). You could create a CSS class with hover style and use the `className` property similarly to how the `style` property is used in the linked file.
