### ISSUE TITLE
Exclude to select

### ISSUE THREAD

**Issue by YuriyDyachkov** [silevis/reactgrid#271]
Hello and thanks for your library!

Tell me is there a way to make a selection without any columns or rows? In this example, I don't want the column with the text "main" to be included in the selection.

![image](https://github.com/silevis/reactgrid/assets/70245262/827f4596-7642-4299-ac93-71e1e15bfed9)

**Comment by DLowHP** [comment]
Hi! If you'd like to validate and optionally prevent the selection you could use [the onSelectionChanging property](https://github.com/silevis/reactgrid/blob/769c115909acf3583fad0c6adeddbfe0e3f7b412/src/lib/Model/PublicModel.ts#L134-L141). If you meant something else just let me know - we'll try to figure it out ;)
