### ISSUE TITLE
Once the sequence number at the beginning of the row is selected, onSelectionChanged cannot be triggered

### ISSUE THREAD

**Issue by qiufeihong2018** [silevis/reactgrid#273]
**Describe the bug**

If enableRowSelection={true}, enableColumnSelection={true}, enableRangeSelection={true} is enabled, onSelectionChanged cannot be triggered after the sequence number at the beginning of a row is selected

![onSelectionChanged-old](https://github.com/silevis/reactgrid/assets/36500514/f7865e13-624c-4907-82ee-3b078b441ac9)

**Current behavior**
A clear and concise description of what you current see.

**Expected behavior**
onSelectionChanged is triggered after the first sequence number of the row is selected, which facilitates subsequent operations on the selected range

![onSelectionChanged-new](https://github.com/silevis/reactgrid/assets/36500514/e5fad57e-2804-40e3-a2b5-351776c5cdae)

**Screenshots or gifs**

**Your environment details**
 - Device:  [e.g.desktop]
 - Browser [e.g. chrome]

**Comment by MichaelMatejko** [comment]
Thanks for your contribution @qiufeihong2018 👍

**Comment by MichaelMatejko** [comment]
@DLowHP to be tested :)
