### ISSUE TITLE
Uncaught ReferenceError: Cannot access 'ReactGrid' before initialization

### ISSUE THREAD

**Issue by qiufeihong2018** [silevis/reactgrid#275]
**Describe the bug**
yarn 
```
   "dependencies": {
+    "react": "^18.2.0",
+    "react-dom": "^18.2.0",
     "sass": "^1.62.1",
     "tslib": "^2.5.2"
   }
```
An error is reported after starting the project

<img width="1495" alt="image" src="https://github.com/silevis/reactgrid/assets/36500514/19bf7e19-08d9-4bb7-89f4-bff1ba716aa2">

**Current behavior**
A clear and concise description of what you current see.

**Expected behavior**

**Screenshots or gifs**

**Your environment details**
 - Device:  [e.g.desktop]
 - Browser [e.g. chrome]

**Comment by qiufeihong2018** [comment]
If 
```
- react": `^16.13.1`
- react-dom: `^16.13.1`
```
So

<img width="1055" alt="image" src="https://github.com/silevis/reactgrid/assets/36500514/6061eb98-d83d-4bd7-9311-87f29e902607">


<img width="563" alt="image" src="https://github.com/silevis/reactgrid/assets/36500514/58854ed6-5783-44ec-a173-846e9da22fa6">

**Comment by MichaelMatejko** [comment]
ReactGrid is built with React 18 but the library (on npm) should be compatible with React 16.

**Comment by qiufeihong2018** [comment]
@MichaelMatejko Hi，createRoot is one of the new features introduced in React 18. If you are still using a version lower than 18.0.0, you will not be able to use createRoot and you should continue to use ReactDOM.render to create the root node. If you use react 16, you need to use ReactDOM.render to create the root node.

**Comment by qiufeihong2018** [comment]
Is there any conclusion to this

**Comment by qiufeihong2018** [comment]
Why does the same branch develop the same set of code, local startup error, cloud server startup normal

online：
<img width="1387" alt="image" src="https://github.com/silevis/reactgrid/assets/36500514/1b51a8ed-6013-4a1e-b3f0-0354c34d9d59">
<img width="1326" alt="image" src="https://github.com/silevis/reactgrid/assets/36500514/8096b352-234f-4a1f-86f9-ec0fdca0ffa6">
local：
<img width="1030" alt="image" src="https://github.com/silevis/reactgrid/assets/36500514/f4c9be09-c6c8-4bd2-9a4b-6ed2e7e13053">

**Comment by qiufeihong2018** [comment]
I do not know if there is a problem with the computer environment, now it is solved, specially to record, restart the computer a few times, you can solve this problem
