### ISSUE TITLE
Can I get selected fields value using "enableRangeSelection" in OnChange() method.

### ISSUE THREAD

**Issue by ayankapadiya** [silevis/reactgrid#277]
**Describe the bug**
"**enableRangeSelection**": When selecting columns value is not able to redirect in the change method.

**Expected behavior**
"**enableRangeSelection**": I want selected field values in a change method like the "**enableFillHandle**" function.

**Screenshots or gifs**
![range selection](https://github.com/silevis/reactgrid/assets/145652510/98680130-377a-4cce-b383-b93655a038de)

**Your environment details**
 - Device: "react": "^18.2.0",
                 "react-dom": "^18.2.0",
 - Browser = chrome

**Comment by qiufeihong2018** [comment]
I don't know if I understand this correctly, can you use handleSelectionChanged to store select rows, onChange when consuming?

**Comment by DLowHP** [comment]
You could try to use [onSelectionChanging/onSelectionChanged](https://github.com/silevis/reactgrid/blob/769c115909acf3583fad0c6adeddbfe0e3f7b412/src/lib/Model/PublicModel.ts#L126-L141) callback and using the selected ranges provided get and/or set values for the selected cells.

**Comment by Michota** [comment]
No answer from @ayankapadiya for 2 weeks now. 
I will close this issue. You may reopen it if there is a reason for it, or if you have question that is related to it.
