### ISSUE TITLE
Copy a range of cells and paste it into another range, extending the target range if it is too small.

### ISSUE THREAD

**Issue by qiufeihong2018** [silevis/reactgrid#280]
**Describe the bug**

**Current behavior**
A clear and concise description of what you current see.

**Expected behavior**

**Screenshots or gifs**

**Your environment details**
 - Device:  [e.g. mobile/desktop]

**Comment by Michota** [comment]
[We already were asked about it not so long ago](https://github.com/silevis/reactgrid/issues/236). We don't plan to add this feature in v4. Though we will think about adding this behavior to v5 of ReactGrid. 
If your data overflows the grid, **you can handle this behavior outside of ReactGrid, in your own function**.
But if you are interested to add feature like this to your project that depends on ReactGrid, I suggest you to create a fork, or implement it by yourself by using something like [PatchPackage](https://www.npmjs.com/package/patch-package).
