### ISSUE TITLE
Pasting from Context Menu trims numeric values

### ISSUE THREAD

**Issue by steve-finbio** [silevis/reactgrid#282]
**Describe the bug**
When using the Paste function from the right-click Context Menu with default menu options (Cut, Copy, Paste) on numeric values, everything after the comma is truncated. 

**Current behavior**
Normal keyboard copy/cut/paste works fine. Context menu copy/cut works fine. But when using the right-click context menu to paste, it truncates the numeric values. Essentially anything after the comma if value is greater than 999.99 is truncated.

**Expected behavior**
Pasting numeric values from the right-click context menu should not truncate anything and paste the exact value copied.

**Screenshots or gifs**
![copy_paste_bug](https://github.com/silevis/reactgrid/assets/132863421/78361bf0-64d9-408a-a5dc-d1e4d0be3bce)

**Your environment details**
 - Device:  Desktop
 - OS: macOS
 - Browser Chrome/Chromium
 - React 18.2.0, Next.js 12.1.4

**Comment by Michota** [comment]
Have you tested it out by yourself, on own product/app/test-environment?
I did, and it seems that the problem is related only to example displayed on ReactGrid.com website, on this certain example, but i can't recreate this issue on different examples.
![chrome_E0wreVC8Bh](https://github.com/silevis/reactgrid/assets/109215822/3374ec39-a03b-4d50-bffa-b1941cb93a33)

#edit: i think i get, it, tho it took me a while.

**Comment by Michota** [comment]
![chrome_Hk8WlwmSbF](https://github.com/silevis/reactgrid/assets/109215822/5c5c40a9-d5d5-4b84-ab38-7f9a47a1ac06)

**Comment by Michota** [comment]
I think it may not be related to parsing on pasting, but to cell formatting, but i will further investigate that.

**Comment by Michota** [comment]
It was so easy to fix, yet it took me a while to find this bug, and create a parser that will work as intended.

Bug fixed.

**Comment by Michota** [comment]
This time i actually managed to resolve this issue, as well as many others bugs related to it.

**Comment by steve-ochoa** [comment]
Amazing work @Michota!!
