### ISSUE TITLE
Initial render does not display all rows

### ISSUE THREAD

**Issue by steve-ochoa** [silevis/reactgrid#284]
**Describe the bug**
Even though rowsToRender contains all the rows we want to render, the initial rendering (very first one) does not display all of them. 

**Current behavior**
rowsToRender are not all rendered/displayed when first loaded. If the user interacts with the grid, then it immediately displays all the rows. It seems to only be able to display 18 or so rows at first. 

**Expected behavior**
Upon first loading a react-grid instance, all rowsToRender should be displayed immediately. 

**Screenshots or gifs**
![render_bug](https://github.com/silevis/reactgrid/assets/8741807/22a291e7-d77c-4e10-9b8b-fa78b5702c74)

**Your environment details**
 - Device:  Desktop
 - OS: macOS
 - Browser: Chrome/Chromium
 - React 18, Next.js 12

**Comment by qiufeihong2018** [comment]
@steve-ochoa Could you provide me with this example? So we can reproduce it

**Comment by Michota** [comment]
I could not reproduce this bug. Did you tried to reproduce it with newest v4 release @steve-ochoa?

**Comment by steve-ochoa** [comment]
@qiufeihong2018 @Michota I was able to reproduce it with the example on the site. I do have the latest v4 running on my own app. I added many child rows to the table and then was able to get the behavior I described (not rendering all rows initially, only when the table is resized or another action is taken does it then re-render all the rows). I'm not sure if it's in the library itself or in the example functions/helpers/etc. Currently I am using the code from the example functions/helpers/etc in my local app as well. Any help is greatly appreciated, this example in particular is awesome, nowhere else is there a collapsing year/quarter view grid like this :) I am using Chrome latest as of Jan 11 2024

![render_bug_ex](https://github.com/silevis/reactgrid/assets/8741807/28810c92-09b9-4e48-80ba-cbec3fcbd843)

**Comment by qiufeihong2018** [comment]
I don't quite understand what you mean. The example of budget planner on the official website seems to have no problem. I see that you have hidden the rows and columns by folding them

**Comment by steve-finbio** [comment]
> I don't quite understand what you mean. The example of budget planner on the official website seems to have no problem. I see that you have hidden the rows and columns by folding them

@qiufeihong2018 @Michota 
Here is a more clear GIF so I can convey the bug. First I unfold, but the bottom of the table is blank/rows unrendered where my cursor moves in circles. Then when I scroll horizontally, the unrendered rows magically appear. Hopefully this conveys what I am describing. 

![render_bug_ex3](https://github.com/silevis/reactgrid/assets/132863421/0b714f41-c970-49d8-bd57-648b06bceee7)

**Comment by steve-ochoa** [comment]
@Michota @qiufeihong2018 I think I named this issue in a misleading way, maybe I can update it or create a new one. I believe this case only occurs when there are Chevrons unfolded. The bug shown in the gif occurs when a Chevron cell is unfolded. It also occurs when `expanded=True` is set for that Chevron cell so it is initially rendered unfolded. 
The blank rows then magically appear when scrolling, interacting with the grid (e.g. clicking another chevron for the years column header expansion) or resizing the window. 
![render_bug_ex4](https://github.com/silevis/reactgrid/assets/8741807/4345f463-602b-4882-b761-82948101c10a)

**Comment by steve-ochoa** [comment]
Recreating with more accurate description and gif
