### ISSUE TITLE
May I ask if there is a bus schedule for the release of the version, if there is, the user does not need to ask when it will be released

### ISSUE THREAD

**Issue by qiufeihong2018** [silevis/reactgrid#285]
**Describe the bug**

**Current behavior**
A clear and concise description of what you current see.

**Expected behavior**

**Screenshots or gifs**

**Your environment details**
 - Device:  [e.g. mobile/desktop]

**Comment by Michota** [comment]
Are you asking about the release date of first non-dev ReactGrid v5.x.x?

**Comment by qiufeihong2018** [comment]
@Michota No, I want to know about the V4 release schedule so that I can upgrade my app

**Comment by DLowHP** [comment]
Given the fact that we have 19 issues open and we are in the holiday season right now I wouldn't expect us to release a new version for the next two or so weeks.

**Comment by qiufeihong2018** [comment]
@DLowHP 🎄🙏I suddenly remembered that you this time is Christmas, like our Chinese Spring Festival to holiday, happy holiday. I was just wondering if there's a release schedule, but if not, you can make one. For example, three weeks later, after the known problem is solved, you can send a version, which is convenient for users to use. I will try my best to mention pr for my problems, you can help cr, thank you
