### ISSUE TITLE
When the last line is bottomed, the right-click context menu is also bottomed, and the menu item is covered and cannot be selected

### ISSUE THREAD

**Issue by qiufeihong2018** [silevis/reactgrid#286]
**Describe the bug**

<img width="919" alt="image" src="https://github.com/silevis/reactgrid/assets/36500514/b58a8c9e-d83f-4757-8966-409d0afa5874">

**Current behavior**
A clear and concise description of what you current see.

**Expected behavior**

**Screenshots or gifs**

**Your environment details**
 - Device:  [e.g. mobile/desktop]

**Comment by qiufeihong2018** [comment]
I'll take care of that

**Comment by Michota** [comment]
Merged into develop branch (PR #287).
