### ISSUE TITLE
Question/Feature request - Update state on keyDown

### ISSUE THREAD

**Issue by gpilla321** [silevis/reactgrid#288]
Is it possible to update the state onKey down? I will explain my scenario:

I've implemented the grid as the documentation, and then I've created a button to send the data in the grid to the API when it is clicked.
Every time the onChange event is triggered, I store the state on the client side (until the button gets hit). The problem is this update state is only triggered on focusOut. So, in case the user writes something in the cell, and doesn't focus out, the last cell value is not stored in time to be sent to the API.

Is there any solution that I can do?
I took a look in the code, and I couldn't find any property that could update the state on keyDown. 

_If there's no solution for now_, I would like to make a code change proposal to fix this, but I have a question. 

I found out that Cells is updated onBlur here (TextCell example). 
https://github.com/silevis/reactgrid/blob/develop/src/lib/CellTemplates/TextCellTemplate.tsx#L74 

And then, this method sends the update
https://github.com/silevis/reactgrid/blob/develop/src/lib/Components/CellEditor.tsx#L58

Why "commit" is required? Running some tests, and removing this should be enough for my scenario, but I am pretty sure that there's a reason to have this. 

Thanks!
Awesome library

**Comment by Michota** [comment]
The CellTemplates are created so users can use them without a need for coding them from scratch, but if you want to change default behavior of the template, you can. Just do it the way you want to.
In your case, all you need to do (I might be wrong though) is to add an `onCellChanged` function to `onKeyDown` in certain (chosen by you) CellTemplate. 

Commit is required to check if user wants to edit this cell, or if he changed his mind.
