### ISSUE TITLE
Working Example of MultiUsers

### ISSUE THREAD

**Issue by Smartauto** [silevis/reactgrid#295]
We want to use Reactgrid  to edit the data.
The editing will be done by simultaneously by multiple users.

though it is mentioned in website that reactgrid support multiple users, we would like to see a working example. It will be nice if you can share a link of code where multi users are able to work on same data.

**Comment by DLowHP** [comment]
The example shown on our website obviously just virtualizes the changes, but the logic for updating the state on new changes should be very similar to real use case based on (for example) web sockets. You can analyze its [source code](https://github.com/silevis/reactgrid-website/tree/9197ee0502269c4a72e675b1c5d8f3664ae86151/src/samples/samplesSrc/datagridSample) on the website repo. In the future we _might_ provide a source code with some changes synchronization solution if needed, but at the moment all I can provide is the aforementioned example source.
