### ISSUE TITLE
The v5-dev branch failed to start

### ISSUE THREAD

**Issue by qiufeihong2018** [silevis/reactgrid#299]
**Describe the bug**
TypeError: get(...).cells.get is not a function at Object.getCellByIds

**Expected behavior**
Normal start-up

**Screenshots or gifs**

<img width="819" alt="image" src="https://github.com/silevis/reactgrid/assets/36500514/f1d4b8e4-db49-432d-b25d-8274fbc15013">

**Your environment details**
 - Device:  [e.g.desktop]
 - Browser [e.g. chrome]

**Comment by Michota** [comment]
Did you tried to start it by using `npx ladle serve`?

**Comment by DLowHP** [comment]
Yeah, the default command remained unchanged. To run the project you should use `(npm | pnpm | yarn) ladle serve`. I created #300 that updates the project to make it more obvious.
