### ISSUE TITLE
onCellsChanged typeerror following "Handling Data Changes"

### ISSUE THREAD

**Issue by Bijig0** [silevis/reactgrid#306]
**Describe the bug**
When following the docs https://reactgrid.com/docs/4.0/2-implementing-core-features/1-handling-changes/, I am getting the type error when assigning `handleChanges` to `onChange`

```
No overload matches this call.
  Overload 1 of 2, '(props: ReactGridProps | Readonly<ReactGridProps>): ReactGrid', gave the following error.
    Type '(changes: CellChange<TextCell>[]) => void' is not assignable to type '(cellChanges: ({ readonly rowId: Id; readonly columnId: Id; readonly type: "checkbox"; readonly previousCell: CheckboxCell & Cell; readonly newCell: CheckboxCell & Cell; } | ... 7 more ... | { ...; })[]) => void'.
      Types of parameters 'changes' and 'cellChanges' are incompatible.
        Type '({ readonly rowId: Id; readonly columnId: Id; readonly type: "checkbox"; readonly previousCell: CheckboxCell & Cell; readonly newCell: CheckboxCell & Cell; } | ... 7 more ... | { ...; })[]' is not assignable to type '{ readonly rowId: Id; readonly columnId: Id; readonly type: "text"; readonly previousCell: TextCell; readonly newCell: TextCell; }[]'.
          Type '{ readonly rowId: Id; 
```

**Current behavior**
A clear and concise description of what you current see.
Type Error

**Expected behavior**
No type error

**Screenshots or gifs**

<img width="575" alt="Screenshot 2024-01-04 at 11 55 02 PM" src="https://github.com/silevis/reactgrid/assets/76978374/eeb621f6-b2bc-4728-b789-55292cd56be4">

**Your environment details**

Chrome desktop

**Comment by qiufeihong2018** [comment]
> **Describe the bug** A clear and concise description of what the bug is. When following the docs https://reactgrid.com/docs/4.0/2-implementing-core-features/1-handling-changes/, I am getting the type error when assigning `handleChanges` to `onChange`
> 
> ```
> No overload matches this call.
>   Overload 1 of 2, '(props: ReactGridProps | Readonly<ReactGridProps>): ReactGrid', gave the following error.
>     Type '(changes: CellChange<TextCell>[]) => void' is not assignable to type '(cellChanges: ({ readonly rowId: Id; readonly columnId: Id; readonly type: "checkbox"; readonly previousCell: CheckboxCell & Cell; readonly newCell: CheckboxCell & Cell; } | ... 7 more ... | { ...; })[]) => void'.
>       Types of parameters 'changes' and 'cellChanges' are incompatible.
>         Type '({ readonly rowId: Id; readonly columnId: Id; readonly type: "checkbox"; readonly previousCell: CheckboxCell & Cell; readonly newCell: CheckboxCell & Cell; } | ... 7 more ... | { ...; })[]' is not assignable to type '{ readonly rowId: Id; readonly columnId: Id; readonly type: "text"; readonly previousCell: TextCell; readonly newCell: TextCell; }[]'.
>           Type '{ readonly rowId: Id; 
> ```
> 
> **Current behavior** A clear and concise description of what you current see. Type Error
> 
> **Expected behavior** A clear and concise description of what you expected to happen. No type error
> 
> **Screenshots or gifs** If applicable, add screenshots to help explain your problem.
> 
> <img alt="Screenshot 2024-01-04 at 11 55 02 PM" width="575" src="https://private-user-images.githubusercontent.com/76978374/294185019-eeb621f6-b2bc-4728-b789-55292cd56be4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MjY5NzgsIm5iZiI6MTcwNDQyNjY3OCwicGF0aCI6Ii83Njk3ODM3NC8yOTQxODUwMTktZWViNjIxZjYtYjJiYy00NzI4LWI3ODktNTUyOTJjZDU2YmU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDAzNTExOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwZTg0MDExZTc3OGU1YjcyODFmNzI1YjZkMTRjNmQyZjZlOTkzOTdkYWFkNTkzYjUzY2IwMDBiNzY5YWIzMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._qKAMIv_2pH3W375kTW4XdBfzlVUVj9JA1SchOeVs3g">
> **Your environment details**
> 
> Chrome desktop

An error might mean something like this: your function only handles TextCell type changes, but your component needs a function that handles changes including CheckboxCell and many other types.

**Comment by DLowHP** [comment]
This is related to #128. I posted a solution for this in the mentioned issue's [comment](https://github.com/silevis/reactgrid/issues/128#issuecomment-1827759609).
