### ISSUE TITLE
onBeforeAutofill

### ISSUE THREAD

**Issue by benhornshaw** [silevis/reactgrid#311]
Hi
is it possible to add an event listener to get the event before an autofill.
the event should give the properties of the selected cell or cells and the calculated outcome to fill.
but it should allow for the fill to be edited and returned just like the onCellsChanged event does.

It would also be good to be able to limit the direction of the fill handle. just Horizontal or vertical.

Any ideas how to make this happen?

Thanks in advance!

**Comment by DLowHP** [comment]
Hi! It's not possible and isn't planned for the v4. On the other hand we've come up with different approach for the fill handle in the v5 version so it should be possible in the future.

**Comment by MichaelMatejko** [comment]
will be part of v5
