### ISSUE TITLE
Performance optimization: The number of table rows reaches more than 5000, even if virtual scrolling is turned on, editing and updating cells is still very slow

### ISSUE THREAD

**Issue by qiufeihong2018** [silevis/reactgrid#313]
**Describe the bug**
The number of rows in the table reaches more than 5000, even if virtual scrolling is enabled, editing and updating cells is still very slow

**Expected behavior**
Optimize it for performance and update it to the millisecond level

**Screenshots or gifs**
![image](https://github.com/silevis/reactgrid/assets/36500514/7b1899f2-4108-4aaf-8626-ee9265420ce6)

**Your environment details**
 - Device:  [e.g.desktop]
 - Browser [e.g. chrome]

**Comment by qiufeihong2018** [comment]
@Michota @DLowHP Do you have any good plans?

**Comment by DLowHP** [comment]
ReactGrid was not designed to be a database. I think the safe limit should be around 25k cells - which is already a lot - as any more than that is barely comprehensible to the average person.
We are open to suggestions for optimizing RG, but at the same time I believe that we are more focused on delivering feature-packed yet highly customizable solution, and performance is _not_ our _main_ concern.
