### ISSUE TITLE
Chevron unfolding produces blank table portion until further interaction

### ISSUE THREAD

**Issue by steve-ochoa** [silevis/reactgrid#318]
**Describe the bug**
This bug occurs when using a Chevron cell grid. When a Chevron is unfolded, the table is sized correctly but a number of rows at the bottom of the table appear blank. When another interaction occurs, e.g. another chevron is unfolded, user scrolls horizontally, or window resized, then the blank rows magically appear. 

**Current behavior**
I produced the behavior using the ReactGrid website Budget Planner example [here](https://reactgrid.com/examples). 
I added many child rows at several levels in the hierarchy of the grid. When I click the Chevron icon to unfold a cell and display its children, there is a large portion left blank at the bottom of the table. The table is sized correctly, so it is clear that the rows are not supposed to be blank. 
Then when using the scroll bar, resizing the window, or interacting with other Chevrons, the blank rows at the bottom of the table magically appear. 
Unfolding and folding Chevrons produces similar blank portion at the bottom of the table with further interactions. Likewise, scrolling/chevron unfolding/window resize causes the blank rows to magically appear. So it appears it's not just a one-time initial render issue. 
It may be in the helper functions for that specific Budget Planner example, I'm unsure. 

**Expected behavior**
When clicking a Chevron to unfold, all rows in the table should be rendered. There should be no blank portion at the bottom. 

**Screenshots or gifs**
![render_bug_ex4](https://github.com/silevis/reactgrid/assets/8741807/6fb64b27-8945-4aec-9018-a88bcf375320)

**Your environment details**
 - Device:  Desktop
 - OS: macOS
 - Browser: Chrome

**Comment by DLowHP** [comment]
Hi! I investigated the issue and, as you've reported, some rows stay invisible after toggling the chevron _on the examples page_. Unfortunately I couldn't reproduce it outside our website. I copied that example's source to our project and it works as intended. 

![chrome_C6Xwe40n2C](https://github.com/silevis/reactgrid/assets/65829376/5d9d2f0d-f5f0-4e73-8f69-2d6d937cb4e6)

Have you experienced similar problems outside our page? If so please let us know.
