### ISSUE TITLE
Native select will not remain open

### ISSUE THREAD

**Issue by warrenday** [silevis/reactgrid#324]
**Describe the bug**
Unable to open native select element due to grid re-render

**Current behavior**
When rendering a native select element, clicking the select causes a re-render which causes the select to close 

**Expected behavior**
Select element remains open. I can see in the example here a native select, however I can not find the source code for the example
https://reactgrid.com/examples/?example=customization

**Screenshots or gifs**
https://github.com/silevis/reactgrid/assets/2871038/6f71ec33-f430-4c1b-aa2a-3a3f352fd1ea

**Comment by Michota** [comment]
Can you create a branch for this issue?

**Comment by Michota** [comment]
Hello. Is this issue still a thing? 
If it is, can you provide some example with [CodeSandbox](https://codesandbox.io/)?

**Comment by warrenday** [comment]
Closing as ended up using a different library.
