### ISSUE TITLE
Error when displaying multiple rows

### ISSUE THREAD

**Issue by lamdev03** [silevis/reactgrid#326]
**Describe the bug**
error when displaying multiple rows
![image](https://github.com/silevis/reactgrid/assets/106731270/8df6bb89-571d-4106-ac40-2ba70b28527b)

**Current behavior**
With tables with short rows, it's fine, but with many rows, I often lose the following rows.
But when I zoom out my screen more rows are displayed.
![image](https://github.com/silevis/reactgrid/assets/106731270/257ca651-2429-4ab4-b993-a76309d8f7ea)

**Expected behavior**
I want to be able to see all my rows no matter what screen I'm on

**Screenshots or gifs**
Here is my code
![image](https://github.com/silevis/reactgrid/assets/106731270/ea285ab4-caab-4f68-b11c-231cfb665c39)

**Your environment details**
 - Device:  [desktop]
 - Browser [chrome]

**Comment by DLowHP** [comment]
It seems to be a virtualization problem. It's not the best solution, but you can try adding the `disableVirtualScrolling` flag/property to the ReactGrid component and tell me if it made a difference.

**Comment by lamdev03** [comment]
Thank you, after adding it it was able to display all the rows.

**Comment by DLowHP** [comment]
Good; just remember that this change _might_ introduce some performance problems if a lot of data is passed to the ReactGrid component.
