### ISSUE TITLE
NumberCell saving incorrectly formatted values

### ISSUE THREAD

**Issue by monjunik** [silevis/reactgrid#327]
**Describe the bug**
When entering a formatted value into a NumberCell it's being saved wrong.

**Current behavior**
Let's say you have locale set to `en-GB`, this makes your number formatting to look like this: 13,500.00
When you type manually this value into a cell it's being saved incorrectly as 13.50.

**Expected behavior**
A correct value of 13,500.00 should be saved -> cell should accept formatted values.

**Screenshots or gifs**
https://github.com/silevis/reactgrid/assets/104763053/3bb0d033-9fb9-4354-95b1-293d822cb73e

**Comment by DLowHP** [comment]
This was fixed with #296 but unfortunately our website's RG version wasn't updated to the latest. Does the issue persist in your local project?

**Comment by monjunik** [comment]
Yes, I am using v 4.1.3. The fixed issue was regarding copy/paste, it works fine indeed. The problem is with manual input only.

**Comment by DLowHP** [comment]
Oh, you're right - good catch. I'll make a PR with a fix for this.

**Comment by monjunik** [comment]
Thank you guys.
