### ISSUE TITLE
The custom Settings column is missing

### ISSUE THREAD

**Issue by qiufeihong2018** [silevis/reactgrid#331]
**Describe the bug**
Missing display column Settings, such as
<img width="1018" alt="image" src="https://github.com/silevis/reactgrid/assets/36500514/eb14ba62-3296-4894-80d0-b68adfca445c">

**Expected behavior**
Expect to be able to add display column Settings

**Comment by MichaelMatejko** [comment]
this is not part of ReactGrid. The idea of the library is to provide the grid and functionality to display any data. You can implement any controls outside of the gird and control it that way.
