### ISSUE TITLE
Expect to add a drag handle column

### ISSUE THREAD

**Issue by qiufeihong2018** [silevis/reactgrid#332]
**Describe the bug**
Is it better to provide a configuration to control whether the drag-and-drop handle column is displayed?

<img width="908" alt="image" src="https://github.com/silevis/reactgrid/assets/36500514/c2603324-3988-4dc6-afc1-7d35d0ab27ea">

**Expected behavior**
Expect to add a drag handle column, Convenient for users to drag and drop rows

**Comment by qiufeihong2018** [comment]
I think now there is no handle, users can not find and operation is inconvenient

**Comment by MichaelMatejko** [comment]
v4 is feature complete. We will schedule this feature for v5.

**Comment by qiufeihong2018** [comment]
So let me contribute this capability to v5
