### ISSUE TITLE
Keyboard integration suggestions

### ISSUE THREAD

**Issue by monjunik** [silevis/reactgrid#334]
Hey,
I have a couple remarks regarding the keyboard integration:

1. First, would it be possible to add a functionality to override keyboard shortcuts? I’d like UX to be more Excel-like and it’d require changing some of the shortcuts (e.g. Ctrl + Shift + Arrow instead of Ctrl + Shift + Home). This way everyone could use shortcuts they’re used to instead of learning new ones.
2. Is it possible to make the editing more smooth by being able to edit a cell value and navigate away with arrows without the need to enter/leave the cell edit mode with enter?

Thanks in advance.

**Comment by Michota** [comment]
This will be introduced in ReactGrid v5. 
Example: In [default behavior](https://github.com/silevis/reactgrid/blob/v5-dev/src/behaviors/DefaultBehavior.ts), which is the behavior handling all the inputs from user, there is an import of [`handleKeyDown`,](https://github.com/silevis/reactgrid/blob/v5-dev/src/utils/handleKeyDown.ts). This handler has some basic logic, behaviors and shortcuts inspired by similar logic from well-known grid and spreadsheet programs and applications.
You, as an programmer, will be able to edit it, or create your own handler, just like you will be able to create your own behavior. Basically you can write the features, logic and mechanics of grid from scratch.

At this moment, when you are using v4, i suggest using [PatchPackage](https://www.npmjs.com/package/patch-package) and edit shortcuts and mechanics related to it by yourself. Keep in mind, that soon we will most likely enter maintenance-only-mode for ReactGrid v4.

**Comment by monjunik** [comment]
@Michota thanks a lot for the reply. When do you plan to release v5?

**Comment by Michota** [comment]
Most likely in upcoming week.
