### ISSUE TITLE
Pasting an externally copied negative number into ReactGrid results in a positive number

### ISSUE THREAD

**Issue by ypt** [silevis/reactgrid#347]
**Describe the bug**
1. Copy a negative number from an external text editor (e.g. -80 from VsCode)
2. Paste that number into ReactGrid
3. The number that shows up in ReactGrid is a positive number (e.g. 80)

**Expected behavior**
The number in ReactGrid should be negative at step 3

**Your environment details**
- With Chrome 121.0.6167.184 in MacOS
- This can be reproduced here: https://reactgrid.com/examples/?example=budget-planner

**Comment by qiufeihong2018** [comment]
@ypt  I have a normal, abnormal gif?
<img width="1266" alt="image" src="https://github.com/silevis/reactgrid/assets/36500514/bf87af4d-87ae-43b3-9901-87b25a38badf">

**Comment by ypt** [comment]
@qiufeihong2018, sorry, I'm not seeing your image as a gif animation (I see a static png).

Though, I just tried to reproduce the issue again on the [budget planner page](https://reactgrid.com/examples/?example=budget-planner), and it seems to be working fine there now. However, I _am_ still able to reproduce on a local project in the same browser with ReactGrid v4.1.3 though.

**Comment by qiufeihong2018** [comment]
@ypt What I see is normal, what I cut is png, do you have any abnormal screenshots or gif

**Comment by ypt** [comment]
Thanks for clarifying, I understand what you're asking for now.

Here's a code sandbox that demonstrates the issue.

https://stackblitz.com/edit/react-playground-practice-wgrfyl?file=index.js

And a screen recording, too

https://github.com/silevis/reactgrid/assets/2073178/42edfc82-0725-46c5-b487-427b88a26d7d

**Comment by qiufeihong2018** [comment]
@ypt ok

**Comment by webloopbox** [comment]
There appears to be an issue with the [regular expression](https://github.com/silevis/reactgrid/blob/5c09f366ca6d077a78bbf46892633c47e278b568/src/lib/Functions/parseLocaleNumber.ts#L23C1-L24C132) inside the `parseLocaleNumber` function. It's currently removing all non-digit characters at the start and end of the string, including the negative sign. Let me fix this issue

**Comment by Ashutosh-Raghuvanshi** [comment]
Waiting for this fix to be released? Any timeline or other way to handle for now?

**Comment by webloopbox** [comment]
> Waiting for this fix to be released? Any timeline or other way to handle for now?

The fix has already been released with version 4.1.4
