### ISSUE TITLE
@silevis reactgrid table full width not working

### ISSUE THREAD

**Issue by shiva8843** [silevis/reactgrid#348]
i am using @silevis reactgrid table , i have tried in many ways to achieve the table to fit to my webpage , but right side empty space is getting , i need the above table to be adjusted full screen even if the table consists two columns. please suggest me the solution to to get the full width

below is the screenshot 
![k2a9o](https://github.com/silevis/reactgrid/assets/161428347/83bf3214-5dd4-4a1c-9eba-acbf5b52fbe4)

the above screen shot the example i need the table width should be fit to the page,

thanks in advance, if some one solve my issue

**Comment by MichaelMatejko** [comment]
ReactGrid V4 is getting it's width from the sum of column widths which need to be set by user. There is no auto-width feature.

ReactGrid V5 will be based on html grid and will allow dynamic width.

**Comment by shiva8843** [comment]
> ReactGrid V4 is getting it's width from the sum of column widths which need to be set by user. There is no auto-width feature.
> 
> ReactGrid V5 will be based on html grid and will allow dynamic width.

okay , thank you for your quick response, is react grid V5 is now available??

**Comment by monjunik** [comment]
@MichaelMatejko when do you plan on releasing V5?

**Comment by shivagavireddy** [comment]
present we are using Version 4 , as you said full width will be available on V5 , so iam waiting to update your table with version 5 , we are planning to release within in 20 days, is full width available on v5 ??

**Comment by MichaelMatejko** [comment]
sorry it will be end of Q2
