### ISSUE TITLE
onSelectionChanging not called when column header is selected

### ISSUE THREAD

**Issue by JensenTStava** [silevis/reactgrid#351]
**Describe the bug**
Whenever the user selects any cell both onFocusLocationChanging and onSelectionChanging are called. This is true for all cells  except the column header. When the column header is selected only onFocusLocationChanging is called. This is particularly problematic when enableRowSelection and enableColumnSelection are true as one cannot use the same handler to capture the selected range for both columns and rows. E.g. If a user selects multiple columns, there is no way to tell what is selected as onSelectionChanging and onSelectionChanged are never called.

**Current behavior**
When the column header is selected only onFocusLocationChanging is called, onSelectionChanging and onSelectionChanged are not called even though the selection changed.

**Expected behavior**
onSelectionChanging and onSelectionChanged should be called when a column header is clicked and enableColumnSelection is true.

**Screenshots or gifs**
![image](https://github.com/silevis/reactgrid/assets/4657668/ecf2e391-68de-436a-a46b-ffdd0989d3b9)

![image](https://github.com/silevis/reactgrid/assets/4657668/cdfc6989-746f-4562-8590-f98e6e9dbaaf)

**Your environment details**
 - Device:  MAC
 - OS: 14.2.1 (23C71)
 - Browser: Chrome

**Comment by JensenTStava** [comment]
It looks like there is no `handlePointerUp` function in `ColumnSelectionBehavior.ts` where there is one in `RowSelectionBehavior.ts`. Hence why they seem to function differently. Is it possible to get a version of the below function added to `ColumnSelectionBehavior.ts`?

```
handlePointerUp(
    event: MouseEvent | PointerEvent,
    location: PointerLocation,
    state: State<CellMatrix, Behavior<MouseEvent | PointerEvent>>
  ): State<CellMatrix, Behavior<MouseEvent | PointerEvent>> {
    if (
      state.props?.onSelectionChanging &&
      !state.props.onSelectionChanging(state.selectedRanges)
    ) {
      // Cancel the latest selection
      const filteredRanges = [...state.selectedRanges].filter(
        (_, index) => index !== state.activeSelectedRangeIdx
      );

      return {
        ...state,
        selectedRanges: filteredRanges,
        activeSelectedRangeIdx: filteredRanges.length - 1,
      };
    }

    state.props?.onSelectionChanged &&
      state.props.onSelectionChanged(state.selectedRanges);

    return state;
  }

  handleContextMenu(event: PointerEvent, state: State): State {
    return handleContextMenu(event, state);
  }
}
```

**Comment by qiufeihong2018** [comment]
There is indeed this problem, I fixed the row selection before, this time I will select the column to fix it

**Comment by JensenTStava** [comment]
Thank you! You are awesome!
