### ISSUE TITLE
Copying from excel results in an additional 0 and overrides the cell below

### ISSUE THREAD

**Issue by Shiro00000** [silevis/reactgrid#354]
I suspect this Bug came with the fix from https://github.com/silevis/reactgrid/pull/296 - "Replace parseFloat with parseLocaleNumber, so ReactGrid will respect locale-based separators."

When one copys from excel to notePad, one sees an empty line was pasted below the copyed number. This empty line is parsed in the reactGrid to 0, where it then overrides the cell below the cell, which was pasted in, with this 0. This is a huge problem. 

An empty string should not be parsed to Number.

**Comment by Shiro00000** [comment]
"Number()
The Number() function accepts a string parameter and converts it to an integer or floating point number, or returns NaN (Not a Number) if the input value doesn't represent a number. An interesting thing to note is that zero (0) is returned for an empty string (Number(''))."

found this on https://jasonwatmore.com/post/2021/10/15/vanilla-js-7-ways-to-convert-a-string-to-a-number-in-javascript#:~:text=The%20unary%20plus%20operator%20(%20%2B%20),string%20(%20%2B''%20).

and the pasted number is converted with "Number(trimmedNumberString);"
so an empty string will result in a 0 being pasted into the cell.

**Comment by webloopbox** [comment]
@Shiro00000 Thank you for bringing this to our attention. I've pushed a fix that ensures an empty string won't result in a 0 being pasted into the cell.

**Comment by Terpo** [comment]
@webloopbox 
Your PR does fix that the number is not written as 0 anymore but the effected additional cell is still cleaned:

Before your fix the behavior was:
![image](https://github.com/silevis/reactgrid/assets/4256058/9dd05ed5-d57d-4ac1-bd9b-7a7be6fb143e)
to
![image](https://github.com/silevis/reactgrid/assets/4256058/35a78c83-ef43-4c74-acb9-91ec55061426)
So only the cell with "5" was copied from Excel but two cells in the grid has been affected. So "6" was changed to "5" and "7" was changed to "0".
Now with your fix, the first cell will change from "6" to "5" but the second cell will be cleared from "7" to "NaN"
![image](https://github.com/silevis/reactgrid/assets/4256058/f914c20e-8e1d-4e85-bef8-9d1655a456e8)

But the main issue is still present. Pasting from Excel results in clearing the last cell.

I think the issues itself is the content of the clipboard:
![image](https://github.com/silevis/reactgrid/assets/4256058/1364cde1-5f81-43f1-9830-4c0bf7d35ee9)
Excel adds an additional line at the end of the clipboard by default.

Is it possible to change the behavior that way NaN is handled as "do not change the current content"?

**Comment by webloopbox** [comment]
> Is it possible to change the behavior that way NaN is handled as "do not change the current content"?

The ability to customize how pasted data behaves will be available in V5.
