### ISSUE TITLE
How to programmatically start editing a cell?

### ISSUE THREAD

**Issue by codinronan** [silevis/reactgrid#357]
**Describe the bug**
Hi all so I have searched for quite some time on how to do this, both here and on StackOverflow. I have created a custom cell template, substantially similar to the one in the example here: https://reactgrid.com/docs/4.0/5-create-your-own-cell-template/ (in fact for the moment, nearly identical). I would like to be able to place this cell into editing mode programmatically (please for the moment assume this is the desired UX, I'm asking whether it can be done).

**Current behavior**
I have tried:
* manually handling an "isEditing" flag to manually set the render function to render an input box. This works but produces very strange results, obviously because it's not integrated with ReactGrid's own handlers
* Capturing a reference to the cell element and manually calling `dispatchEvent` with a `MouseEvent` `dblclick` event.

Neither of these produce the desired behavior. The event approach doesn't work at all, and the `isEditing` approach seems to cause several rerenders and ultimately settle on not being editing (and this because the `isInEditMode` flag RG itself provides is never set to true, so I wouldn't expect this to work right).

**Expected behavior**
I must be missing something. There's got to be a way to trigger editing on the cell in a ReactGrid way. (Note I don't care about customizing the edit experience, I'm fine with the default one - I just want a way to get the cell into that state!)

**Comment by MichaelMatejko** [comment]
there is no direct access to reactgrid yet. In v5 it will be possible to control the grid via an api hook
