### ISSUE TITLE
Add a way to deselect rows from code

### ISSUE THREAD

**Issue by MarcusElg** [silevis/reactgrid#358]
**Describe the bug**
After executing a custom action in the context menu I want the row to deselect automatically. After inserting a row for I update the indexes of the rows so that the new row gets a logical index (from 0 to n). This results in a different row being selected, I would rather have all rows be deselected as the action is completed.

**Current behavior**
Some row is still selected

**Expected behavior**
It should be possible to deselect from code.

**Comment by qiufeihong2018** [comment]
This ability is necessary

**Comment by qiufeihong2018** [comment]
Done

**Comment by MarcusElg** [comment]
@qiufeihong2018 Doesn't seam to be possible to import ReactGridInstance (using ReactGrid 4.1.4):

Module '"@silevis/reactgrid"' has no exported member 'ReactGridInstance'.

**Comment by MarcusElg** [comment]
Thought it had been merged into master. Apparently it hasn't

**Comment by MichaelMatejko** [comment]
It is implemented in a strange way but it works and I'll merge it only because we will release v5 and offer a hook to access reactgrid.

**Comment by MichaelMatejko** [comment]
fixed.
