### ISSUE TITLE
Mention the selectedRanges for handleContextMenu in the documentation

### ISSUE THREAD

**Issue by MarcusElg** [silevis/reactgrid#359]
I've added multiple custom actions such as removing a row. This works fine when selecting an entire row, but I would also be able to remove a row just by selecting a single cell, like it works in Google docs. However looking at https://reactgrid.com/docs/4.0/2-implementing-core-features/5-context-menu/ the only inputs are selectedRowIds and selectedColIds. Both these are empty arrays when the selection mode is "range". So how would access the selected positions?

**Comment by qiufeihong2018** [comment]
@MarcusElg In fact, onContextMenu has a fifth parameter, selectedRanges, which is the selection range

<img width="482" alt="image" src="https://github.com/silevis/reactgrid/assets/36500514/7bd55846-e879-4b6f-ad34-2b9c419f7394">

**Comment by MarcusElg** [comment]
> @MarcusElg In fact, onContextMenu has a fifth parameter, selectedRanges, which is the selection range
> 
> <img alt="image" width="482" src="https://private-user-images.githubusercontent.com/36500514/316488111-7bd55846-e879-4b6f-ad34-2b9c419f7394.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNzcyNTIsIm5iZiI6MTcxMTM3Njk1MiwicGF0aCI6Ii8zNjUwMDUxNC8zMTY0ODgxMTEtN2JkNTU4NDYtZTg3OS00YjZmLWFkMzQtMmI5YzQxOWY3Mzk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE0MjkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiZTM4ZjliNTU3ODJmY2U4NTYzOTM0YTM3ODgzZTI1YjljOTYyZjUzMDg3ZDBlZTQyNzY4NDAwMTA0NjYwNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Nh28NzpU5k6AJKi__6pmVo_-nBhpgRU4hhQbWQOIodM">

Great! That should definitely be mentioned in the documentation...

**Comment by qiufeihong2018** [comment]
Done，PR：https://github.com/silevis/reactgrid-website/pull/25

**Comment by krishnamurti-brevitaz** [comment]
@qiufeihong2018 , can you please check this again. I don't see "selectedRanges" mentioned in Docs. Thank you

**Comment by qiufeihong2018** [comment]
@webloopbox Is not yet published？ @krishnamurti-brevitaz

**Comment by webloopbox** [comment]
> @webloopbox Is not yet published？ @krishnamurti-brevitaz

The docs have been recently updated

![image](https://github.com/silevis/reactgrid/assets/60100557/9d7bd65b-eb04-4461-b3e7-24afe69403e2)

**Comment by qiufeihong2018** [comment]
Thank you @webloopbox
