### ISSUE TITLE
Discord invite link in social links is invalid

### ISSUE THREAD

**Issue by JackMcBride98** [silevis/reactgrid#365]
Clicking the link in the social tab. Invalid invite
![image](https://github.com/silevis/reactgrid/assets/37148941/fdbf9de8-5957-4109-9ee1-37af436f9f80)
![image](https://github.com/silevis/reactgrid/assets/37148941/79cce6a5-8e50-4780-9398-0478c57771d6)

**Comment by MichaelMatejko** [comment]
@webloopbox  remove link
