### ISSUE TITLE
Event Handler assumes id is truthy

### ISSUE THREAD

**Issue by mithodin** [silevis/reactgrid#367]
The blur handler at https://github.com/silevis/reactgrid/blob/01d72cf6700b2b3d599759ce713d7ee6c7529b91/src/lib/Model/EventHandlers.ts#L21
assumes that the target element of the event has an id property. If this is not the case (as happens e.g. on click outside of the table), the method throws an error.

This issue is fixed by https://github.com/silevis/reactgrid/pull/366

**Comment by webloopbox** [comment]
@mithodin  I see PR [#366](https://github.com/silevis/reactgrid/pull/366) is closed. Is this problem still actual?

**Comment by mithodin** [comment]
Oh, I deleted the wrong branch. The problem very much persists.

**Comment by mithodin** [comment]
I recreated the branch and created a new pull request: https://github.com/silevis/reactgrid/pull/382
