### ISSUE TITLE
CSS Selector on input overrides material ui styles

### ISSUE THREAD

**Issue by mithodin** [silevis/reactgrid#369]
**Describe the bug**
The styles for any input element which is a child of a `.rg-celleditor` Element get overridden by this rule: https://github.com/silevis/reactgrid/blob/01d72cf6700b2b3d599759ce713d7ee6c7529b91/src/cell-templates.scss#L21
This breaks e.g. the material ui date selector, because `.rg-celleditor input` is more specific than the selectors mui uses to style the input.

**Current behavior**
reactgrid styles apply to material ui input used within a cell in edit mode.

**Expected behavior**
reactgrid should only style element it has created itself, by using a class or other appropriate css selector.

**Screenshots or gifs**
Date Input with overridden styles
![Bildschirmfoto 2024-03-26 um 10 21 26](https://github.com/silevis/reactgrid/assets/3817786/2549dd69-be1d-4e97-a4c2-5b917154e3f7)
Date input when reactgrid's rule is disabled
![Bildschirmfoto 2024-03-26 um 10 22 24](https://github.com/silevis/reactgrid/assets/3817786/3581d0ee-a3bc-473b-a8a0-2d923c295570)

**Comment by qiufeihong2018** [comment]
Do you have a demo？

**Comment by mithodin** [comment]
@qiufeihong2018 sure: https://github.com/mithodin/reactgrid-issue-369
