### ISSUE TITLE
How to put calculations on rows and columns?

### ISSUE THREAD

**Issue by Ajay-gwc** [silevis/reactgrid#372]
How do I get a row or column to have calculated values of other rows or columns. 

I have a parent row of 2 children, I need to have the subtraction or sum of the child rows in the parent row
I need a column with values of difference between 2 other columns, 
If a change the value in one cell, it should reflect in other cells as well if its calculated in other row or column

**Comment by qiufeihong2018** [comment]
I think you want the ability this example provides
https://reactgrid.com/examples/?example=budget-planner

**Comment by Ajay-gwc** [comment]
@qiufeihong2018 , yes that's what I'm trying to get, is there any source code available for that.

**Comment by qiufeihong2018** [comment]
You can see [reactgrid-website](https://github.com/silevis/reactgrid-website)

**Comment by Ajay-gwc** [comment]
@qiufeihong2018, I've cloned the repo and searched through it, but couldn't able to find it. is there any other way to get the source code.

**Comment by Bob7890** [comment]
https://reactgrid.com/docs/4.0/2-implementing-core-features/1-handling-changes/

**Comment by webloopbox** [comment]
Is this issue still in place?

**Comment by Ajay-gwc** [comment]
hi @webloopbox , it can be closed. thanks
