### ISSUE TITLE
Fill handle does not work on dropdown cells

### ISSUE THREAD

**Issue by MarcusElg** [silevis/reactgrid#373]
**Describe the bug**
Copy/cut/fill handle does not work for dropdown cells.

**Current behavior**
Dragging the fill handle over multiple cells select them as if the operation was successful, however the values have not been copied.

**Expected behavior**
The values would be copied

**Screenshots or gifs**
![image](https://github.com/silevis/reactgrid/assets/19669673/06c0d8ae-b5c3-4e02-97dd-94c63947e236)

**Version**
4.1.4

https://github.com/silevis/reactgrid/pull/203 was suppost to fix the issue but it didn't seam to do it.

**Comment by qiufeihong2018** [comment]
Please give me a demo?

**Comment by webloopbox** [comment]
@MarcusElg The fill handle on dropdown cells should work properly with the current version of ReactGrid (4.1.4). The `onCellsChanged` prop accepts a function that handles changes. This function receives an argument representing the changed cells. You should be able to adjust the fill handle operation using it. It would be helpful if you could provide a sandbox that demonstrates your issue.

**Comment by MichaelMatejko** [comment]
works on website
![image](https://github.com/silevis/reactgrid/assets/6450011/fabdecdc-af7e-4844-8069-5a6eeceabc8a)
