### ISSUE TITLE
CodeSandbox examples are broken

### ISSUE THREAD

**Issue by blopez2010** [silevis/reactgrid#38]
**Describe the bug**
Clicking on examples links will take you to a broken example in the code sandbox page https://codesandbox.io/s/reactgrid-creating-new-cell-template-pdiux?file=/src/index.tsx

**Current behavior**
https://codesandbox.io/s/reactgrid-creating-new-cell-template-pdiux?file=/src/index.tsx

**Expected behavior**
Examples should be working for the expected implementation

**Your environment details**
 - Device:  desktop
 - OS: Windows
 - Browser: chrome

**Comment by patryk0493** [comment]
This issue is probably related to the circular dependencies. We working on a fix for this.
