### ISSUE TITLE
How to make the  Dropdown  Searchble?

### ISSUE THREAD

**Issue by Mengeroshi** [silevis/reactgrid#381]
I'm tryng to do a searcheble dropdown modifying the [DropdownCellTemplate](https://github.com/silevis/reactgrid-samples/blob/dev/src/cell-templates/dropdownCellTemplate/dropdownCellTemplate.tsx) and  using [react-select](https://react-select.com) library but I think I'm lost.

Is this possible to make?
what would be the apropiate utils fuctions to use to achive a behaviour like this?

![imagen](https://github.com/silevis/reactgrid/assets/44041766/25438a7f-1817-4b6a-aa91-cf75e2833adb)

**Comment by qiufeihong2018** [comment]
I think you need custom template component?

**Comment by webloopbox** [comment]
@Mengeroshi Please take a look at this [codesandbox](https://codesandbox.io/p/sandbox/reactgrid-searchable-dropdown-example-r3n5l9)

**Comment by Mengeroshi** [comment]
Thank You, I haven't noticed that it was a default behaviour
