### ISSUE TITLE
negative values are not pasted as negative

### ISSUE THREAD

**Issue by Shiro00000** [silevis/reactgrid#385]
**Describe the bug**
copy from excel or text editor resultes in negative values to be casted to positive values

**Current behavior**
when I copy "-1" as String from Excel or text Editor (Windows), it pastes 1 as number into the NumberCell.

**Expected behavior**
I would like that "-1" ist casted to -1 as number in the NumberCell.

**Comment by webloopbox** [comment]
This bug has been fixed within issue #347. New changes are already available in ReactGrid 4.1.4
