### ISSUE TITLE
Copy-pasting cells with white text - invisible output

### ISSUE THREAD

**Issue by mmkal** [silevis/reactgrid#392]
**Describe the bug**

I have a sheet in a dark-mode app, and the text color is white. When I copy a range of cells and paste them into https://sheet.new, they're invisible.

**Current behavior**

White text, and most spreadsheets are white background by default.

**Expected behavior**

It would be great if reactgrid could do one of:

1. capture the dark background as well as the white text
2. don't capture the colours when copy pasting, rely on the destination formatting
3. document how to avoid this problem  

**Screenshots or gifs**

Cropped video of using Cmd-C on reactgrid, then going to Google Sheets and using Cmd-V:

https://github.com/silevis/reactgrid/assets/15040698/0e49b9be-a6b9-4ce8-9989-fb36354bf0c7

Note that the pasting is working fine when pasting values only. It also works fine when doing Cmd-Shift-V but some users won't know to do that and will say it's broken.

**Your environment details**

 - Device:  desktop
 - OS: Mac OS
 - Browser Chrome

By the way - working with reactgrid in general has been fantastic. Thank you!!

**Comment by webloopbox** [comment]
@mmkal We're glad to hear that you're enjoying working with ReactGrid! The behavior you've shown in the video is indeed not expected. The most reasonable solution, as you suggested, is to not capture the colors when copying and pasting. I will create a PR to address this issue
