### ISSUE TITLE
When you edit the cell and scroll, cell is scrolling with you

### ISSUE THREAD

**Issue by 890f2151c2be69c51db72017546d00fd** [silevis/reactgrid#398]
**Describe the bug**
When you edit the cell and scroll, cell is scrolling with you

you do not need demo or example you can test on https://reactgrid.com/examples. just start edit the cell and scroll with mouse wheel

**Expected behavior**
cell should not scroll

**Screenshots or gifs**
video: https://streamable.com/irjiht
not sure how long will be there, I can reupload if needed

**Your environment details**
tested on mac and windows both with latest chrome

**Comment by MichaelMatejko** [comment]
Yes, this is intended behavior. Check also on on Google spreadsheets.
In version 5 we will disable it because there are too many complaints about it.

**Comment by 890f2151c2be69c51db72017546d00fd** [comment]
thank you for fast answer, in that case am closing the issue.
