### ISSUE TITLE
Number Cell Template - How to handle the onKeydown events to input? No props available.

### ISSUE THREAD

**Issue by Asha729** [silevis/reactgrid#408]
**Describe the bug**
Need to prevent the typing in input field if it exceed the maximum limit.

**Current behavior**
No prop to handle the keydown events, only oncellsChanges is available.

**Expected behavior**
Can we add a prop for this?

**Comment by MichaelMatejko** [comment]
Please copy our NumberCell template and create your own based on that. There you can add any event you like to the input field.
