### ISSUE TITLE
Copy/Paste a date from clipboard into ReactGrid Date Cell does not work

### ISSUE THREAD

**Issue by testone740** [silevis/reactgrid#412]
**Describe the bug**
Copying a date value (ex: 12/12/2023) from an external source into ReactGrid Date Cell blanks out the cell.

**Current behavior**
I can copy a date from a ReactGrid Date cell and paste into a different date cell.  When I copy a date value "12/12/2023" from a text editor or Excel into a ReactGrid Date cell, the cell goes blank.

**Expected behavior**
When I copy a valid date string value from a text editor and paste it into a ReactGrid Date cell, the date should be shown as if I typed the date.

**Steps of reproduce**
1. Copy this date value `12/12/2023` into your clipboard
2. Go to Multi-User example (https://reactgrid.com/examples/?example=multi-user)
3. Paste the copied date into a Date Cell either in the `Register` or `Birth Date` column
4. The Date Cell becomes blank

**Your environment details**
 - Device: Desktop
 - OS: Any
 - Browser: Any

**Comment by webloopbox** [comment]
@testone740 
To be able to handle this, you should create your own DateCell template. 
https://reactgrid.com/docs/4.0/5-create-your-own-cell-template/

`cellToMerge` property contains a `text` field, which you can pass as an argument to `getCompatibleCell`:

```
  update(cell: Compatible<DateCell>, cellToMerge: UncertainCompatible<DateCell>): Compatible<DateCell> {
    return this.getCompatibleCell({ ...cell, date: new Date(cellToMerge.value), value: cellToMerge.value });
  }
```

Next, you should appropriately adjust the code within the `getCompatibleCell` method.

**Comment by testone740** [comment]
Got it.  Thanks for the tip.  Here is a slight adjustment.

```
  update(cell, cellToMerge) {
    return this.getCompatibleCell({
      ...cell,
      date: new Date(cellToMerge.text),  // cellToMerge.value is `NaN` when copy a date from outside into a Date Cell
      text: cellToMerge.text,
    });
  }
```
