### ISSUE TITLE
How to clear selected value in a dropdown cell?

### ISSUE THREAD

**Issue by celestial83u83** [silevis/reactgrid#416]
Is there a way to clear a selected value in a dropdown cell? Currently, upon selecting a value from a dropdown, I do not see a way to deselect or clear the cell.

Would it be possible to add an option for an "x" icon or something along those lines to the dropdown cell that would clear that dropdown if a value has been selected?

Example:

![Screenshot 2024-07-16 at 10 49 06 AM](https://github.com/user-attachments/assets/ef14d5d7-b9c6-4ced-9adc-de5b1a33f1ea)

**Comment by webloopbox** [comment]
@celestial83u83 Dropdown cell uses the react-select component, which has an `isClearable` prop, but it is not included by default. To be able to clear selected data, you can create your own [custom dropdown cell](https://reactgrid.com/docs/4.0/5-create-your-own-cell-template/) and override logic from [existing template](https://github.com/silevis/reactgrid/blob/develop/src/lib/CellTemplates/DropdownCellTemplate.tsx).
