### ISSUE TITLE
Cutting a dropdown cell doesn't clear it

### ISSUE THREAD

**Issue by celestial83u83** [silevis/reactgrid#424]
**Describe the bug**
I'm not sure if this is a bug or intended, but if I cut a dropdown cell, it doesn't clear the cell.

**Current behavior**
Cut (cmd/ctrl-x) on a dropdown cell does nothing; the selected value is unchanged. 

**Expected behavior**
Cut (cmd/ctrl-x) on a dropdown cell should clear the cell. 

**Your environment details**
 - Device: Any
 - OS: Any
 - Browser: Any

**Comment by celestial83u83** [comment]
Also clearing with delete/backspace key does nothing either unless you click into the search input field - So I think this might be because the library used for the dropdown cell, `react-select`, does not support clearing via those methods? Correct me if I'm wrong

**Comment by webloopbox** [comment]
@celestial83u83 I have already created a PR for this issue

**Comment by Michota** [comment]
So, if #426 was merged, have you tried testing it, @celestial83u83? Does it work as you expected?

**Comment by celestial83u83** [comment]
> So, if #426 was merged, have you tried testing it, @celestial83u83? Does it work as you expected?

Working as expected now, thanks.
