### ISSUE TITLE
First key press on number cell is not inserted into the cell

### ISSUE THREAD

**Issue by MichaelMatejko** [silevis/reactgrid#43]
**Describe the bug**
First key press on number cell is not inserted into the cell.

**Current behavior**
1. Select number cell
2. Press any number on the keyboard
3. Editor opens but pressed number does not appear

**Expected behavior**
3. Editor opens and pressed number does appear in editor.

**Screenshots or gifs**
![book-demo](https://user-images.githubusercontent.com/6450011/97456665-5c760200-1939-11eb-8ecc-232f221713ea.gif)

**Your environment details**
Tested on Chrome on PC

**Comment by myskamil** [comment]
Thank you for reporting. As we found out, the problem is not in the internal number cell template. If there are any further problems, please report it.
