### ISSUE TITLE
SCSS does not compile with newer versions of sass (starting with 1.77.7)

### ISSUE THREAD

**Issue by samkuehn** [silevis/reactgrid#433]
**Describe the bug**
There was a breaking change in sass (mixed declarations).  Unfortunately, there are a few places where react-grid is effected and will not compile.

Here is an article explaining the issue.
https://sass-lang.com/documentation/breaking-changes/mixed-decls/

Current fix for me is do downgrade sass to a version < 1.77.7
```
npm install sass@1.77.6
```

**Comment by Sturez** [comment]
@samkuehn is right. at line 72 of main.scss file there's a small problem.

this

`                .rg-resize-handle {
                    &:hover {
                        cursor: col-resize;
                        background-color: $resize-handle-gb-color;
                    }

                    position: absolute;
                    right: 0;
                    width: $resize-handle-line-width;
                    height: 100%;
                }`

might become something like this:

`.rg-resize-handle {
                    position: absolute;
                    right: 0;
                    width: $resize-handle-line-width;
                    height: 100%;

                    &:hover {
                        cursor: col-resize;
                        background-color: $resize-handle-gb-color;
                    }
                }`

**Comment by webloopbox** [comment]
@samkuehn This problem has already been fixed [here](https://github.com/silevis/reactgrid/pull/437). You can re-open if still an issue.
