### ISSUE TITLE
NonEditable chevron cell

### ISSUE THREAD

**Issue by krzysztofsaw** [silevis/reactgrid#44]
**Describe the bug**
Cell chevron does not collapse or expand when property 'nonEditable' is set to true.

**Current behavior**
When property 'nonEditable' is set to true. Cell is not editable but i can't collapse or expand options.

**Expected behavior**
Chevron cell is not editable and i can collapse or expand options.

**Your environment details**
 - chrome

**Comment by patryk0493** [comment]
As you see `collapse` attribute is a part of the cell data and it is also managed by `nonEditable` option. If the cell has a `nonEditable` field set to `true`, then is fully non-editable.

**Comment by monjunik** [comment]
Hey, I am struggling with exactly the same issue now. Is there a way to make a chevron cell content not editable but still be able to expand/collapse it? Seems like a basic functionality.
