### ISSUE TITLE
Following documentation, I can't make the `dropdown` and `time` to work

### ISSUE THREAD

**Issue by chneau** [silevis/reactgrid#441]
**Describe the bug**
Following documentation, I can't make the `dropdown` and `time` to work

**Current behavior**
`dropdown` shows the label and a caret to open the select but the options don't show.
`time` is just empty and for some reason the update is not working.

**Expected behavior**
`dropdown` to work like in here https://reactgrid.com/examples/?example=customization when you click on projects.
`time` to show properly the value.

**Screenshots or gifs**
![image](https://github.com/user-attachments/assets/01e06505-a4a1-45a7-9e56-c9fbd4226329)

**Your environment details**
 - Device:  desktop
 - OS: Windows for client, Debian 12 for development server (VSCode SSH remote)
 - Browser Latest Microsoft Edge - Version 129.0.2792.52 (Official build) (64-bit)

**GitHub repo to reproduce**
https://github.com/chneau/bug-silevis-reactgrid

**Comment by webloopbox** [comment]
@chneau It is necessary to update the `isOpen` field of the dropdown cell inside the `onCellsChanged` handler. As I can see in your snippet, you only update the value. Please take a look at this [sandbox](https://codesandbox.io/p/sandbox/reactgrid-searchable-dropdown-example-r3n5l9), it may be helpful.

**Comment by chneau** [comment]
@webloopbox Perfect, thank you so much, I have updated the code and now it's working perfectly :)

For the time, I forgot to use the `time` field and to set a `format`.

![image](https://github.com/user-attachments/assets/08300ce1-8681-4646-8d92-a55002b7adbf)
