### ISSUE TITLE
Strange behavior with F2-F12 keys

### ISSUE THREAD

**Issue by FlorianCassayre** [silevis/reactgrid#443]
**Describe the bug**
When pressing any of the <kbd>F2</kbd> - <kbd>F12</kbd> keys while focusing a cell, the behavior is unexpected:
- In case of a number, the cell briefly displays the name of the key (e.g. `f2`), and then defaults to the empty value once the cell is unfocused
- For any other type, nothing happens (the cell does not even enter edit mode)

**Expected behavior**
Taking a look at Excel or Google Sheets:
- If the key is <kbd>F2</kbd>, then the cells immediately enters edit mode
- For other keys it depends on the software. Google Sheets doesn't bind any of these keys to custom actions, so it defaults to whatever would happen normally. Excel has various shortcuts

So in the end I think it would make sense to replicate Google Sheets' behavior, that is binding <kbd>F2</kbd> to entering edit mode, and for any other key we should simply not handle the event.

Looking at the feedback from our users, it appears to be common knowledge that <kbd>F2</kbd> is used to enter edit mode. I didn't know, but it makes sense since on Excel <kbd>Enter</kbd> is already reserved for moving to the next cell.

**Comment by webloopbox** [comment]
@FlorianCassayre Indeed, the behaviour of the function keys is unexpected. I have already created a PR with the fix

**Comment by FlorianCassayre** [comment]
@webloopbox Wonderful, thanks for the reactivity.

**Comment by FlorianCassayre** [comment]
Tested on our side, works well. This ticket can be marked as resolved, thanks again.
