### ISSUE TITLE
SASS fails to compile due to deprecation warnings using the latest version of SASS (1.79.4)

### ISSUE THREAD

**Issue by samkuehn** [silevis/reactgrid#445]
lighten(), darken() are deprecated in favor of color.scale($color, $lightness: 92.96875%)

SEE:
https://sass-lang.com/d/color-functions

lighten is used here:
@silevis/reactgrid/default-colors.scss:21:33

darken is uesed here:
@silevis/reactgrid/main.scss:197:34

**Comment by nltheme** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
