### ISSUE TITLE
Editable Cell position is fixed relative to screen.

### ISSUE THREAD

**Issue by g1kum4r** [silevis/reactgrid#451]
**Describe the bug**
double click on cell, to make it editable, and then scroll the page, the editable cell is fixed relative to screen. 

**Current behavior**
double click on cell, to make it editable, and then scroll the page, the editable cell is fixed relative to screen. 

**Expected behavior**
editable cell position shouldn't be fixed to screen, it must be relative to cell 

**Screenshots or gifs**

https://github.com/user-attachments/assets/d7e487cc-6f66-4349-83bb-77b74a566d49

**Your environment details**
 - Device:  [e.g. mobile/desktop] - Desktop
 - OS: [e.g. iOS] Windows 11
 - Browser [e.g. chrome, safari] chrome

**Comment by MichaelMatejko** [comment]
Actually this is a feature not a bug. Please check Google Sheets is doing the same thing. 

In v5 this feature is not available anymore. 
https://silevis.github.io/reactgrid/
