### ISSUE TITLE
Formulas in reactgrid

### ISSUE THREAD

**Issue by DevCraftsmanShubham** [silevis/reactgrid#62]
**Expected behavior**
 https://reactgrid.com/examples/?example=athletes-exercises
I want to create a sheet with formulas like you have shown in the athletes example. I am not sure how to implement this, I tried to find the example code, but I am not seeing anywhere.
could you please provide me an example of how can i implement formulas as I have seen in the athletes example

**Comment by myskamil** [comment]
Hello @sk1794! 
We are very happy that you are working with ReactGrid. Our website is in our public repo and you can find there implementations of our examples used in the website. You can find Athlete exercise implementation [here](https://github.com/silevis/reactgrid-website/tree/gh-pages-dev/src/samples/samplesSrc/excercisesDataSample).
