### ISSUE TITLE
License prop on ReactGrid

### ISSUE THREAD

**Issue by miki10194** [silevis/reactgrid#64]

**Comment by MichaelMatejko** [comment]
As the provider I want to ensure that the user has licensed the software properly. Therefore there should be a licence prop on the ReactGrid component.
There are two ways to enable ReactGrid. 
1) license='non-commercial'
2) license='N developers until YYYY-MM-DD issued for COMPANY NAME // HASH'

**Comment by patryk0493** [comment]
Added feature branch with this functionality: [https://github.com/silevis/reactgrid/tree/feature/license-prop](url)
