### ISSUE TITLE
[feature request] Wrap text

### ISSUE THREAD

**Issue by hunterwilhelm** [silevis/reactgrid#75]
**Describe the feature**
I cannot seem to find the wrap text feature for cells in a column. Here is how it works in Excel. Is there a way to do this? If not, I would like to request this feature.

**Current behavior**
All cells are unwrapped making paragraphs difficult to edit.

**Expected behavior**
A flag for columns to make the wrap text feature similar to how Microsoft Excel wraps the text.

**Screenshots or gifs**
Her is a screenshot of how it is displayed in Excel.
<img width="1552" alt="Screen Shot 2022-03-03 at 10 56 46 AM" src="https://user-images.githubusercontent.com/71348224/156623585-acb6c055-c018-489b-a43e-a76408422214.png">

**Comment by czerwiukk** [comment]
Hello!
The feature is achievable by creating a cell template which would render cell data in a div with desired css settings.
You can also replace the edit mode behavior, e.g. by using text area instad of a plain input.
[Read more here](https://reactgrid.com/docs/4.0/5-create-your-own-cell-template/)

**Comment by sabino-ramirez** [comment]
@czerwiukk I tried your solution with a custom renderer that does what you suggested. However, the size of the row does not change. How would you get the row height to respect the space needed for the wrapped text in that cell?

**Comment by DLowHP** [comment]
Hi, I investigated this issue and created [this sandbox](https://codesandbox.io/s/reactgrid-textwrap-cell-cnylcd). My solution is not an official one and was created only to verify if such functionality is possible with current API. Do not use this in its current form, it needs refactoring, testing and additional handling of edge cases. Albeit, I hope it at least helps you find the proper direction. Please take a look and let me know ;)

**Comment by sabino-ramirez** [comment]
Hi @DLowHP. Your sandbox is very promising. As you said, the functionality is possible and that is what is important. Thank you for taking the time!

**Comment by DLowHP** [comment]
You're welcome! I will close the issue now, if you need anything more just text me! ;)
