### ISSUE TITLE
Dropdown is not working

### ISSUE THREAD

**Issue by ricardoalexander** [silevis/reactgrid#76]
**Describe the bug**
Dropdown is not working

**Current behavior**
Clicking on the dropdown doesn't show the selection popup

**Expected behavior**
The dropdown selection will open

**Screenshots or gifs**

**Your environment details**
 - Device:  desktop
 - OS: windows
 - Browser: chrome

**Comment by hunterwilhelm** [comment]
I am having this problem too.

Here is a sandbox that shows the issue

https://codesandbox.io/s/jolly-galileo-jivsd2?file=/src/App.tsx

**Comment by czerwiukk** [comment]
Hi guys! Thank you for reporting this issue.  
In the current implementation of the Dropdown Cell, the user has to keep the state of the dropdown on his own.
The cell expects to receive `isOpen` property within the cell, like this:
```
{
  type: "dropdown",
  selectedValue: person.name,
  inputValue: person.name,
  isOpen: true /* or false */,
  values: getPeople().map((p) => ({ label: p.name, value: p.name }))
},
```
I can see that it's not described in the docs, so thank you again for pointing this out.
If this behavior doesn't meet your needs, you can always create and use your own dropdown cell.

**Comment by hunterwilhelm** [comment]
@czerwiukk Thank you! For those that need an example of what the suggestion is, here is my sandbox. 

Look for the comments that say `// CHANGED:` because those lines are the important parts

https://codesandbox.io/s/silevis-reactgrid-working-dropdown-example-ow9j2c?file=/src/App.tsx

**Comment by hunterwilhelm** [comment]
Here is another example that doesn't modify the person interace. Instead, we hold a dropbox opened location state with useState and set it when something opens.

https://codesandbox.io/s/silevis-reactgrid-better-generic-dropdown-ue7wph?file=/src/App.tsx

**Comment by karan316** [comment]
Why is this not a part of the default behaviour of the DropdownCell?
