### ISSUE TITLE
hover for header names

### ISSUE THREAD

**Issue by poliver-limit** [silevis/reactgrid#77]
**Describe the bug**
If the label of a column does not fit in the column, the cut name is displayed.
It would be nice to define a property for header that allows displaying a description of the column when hovering over the column label. For example:
![image](https://user-images.githubusercontent.com/72934060/157274392-ed80ec99-9131-4caf-9a13-465aa9394820.png)

**Current behavior**
Currently, a hover over the column is not displayed. If the width of the column is short, the name is not displayed correctly.

**Expected behavior**
Currently, a hover over the column is not displayed. If the width of the column is short, the name is not displayed correctly.
![image](https://user-images.githubusercontent.com/72934060/157274392-ed80ec99-9131-4caf-9a13-465aa9394820.png)

**Comment by czerwiukk** [comment]
Hi! Thank you for coming up with this idea.
Currently we're not working on new features, but we'll take it into consideration.
Feel free to contribute if you feel like implementing it.
