### ISSUE TITLE
Sass variable $cell-border-color is not used for styling cell borders

### ISSUE THREAD

**Issue by joshuanathanson** [silevis/reactgrid#78]
**Describe the bug**
Using the Sass variable $cell-border-color does not result in border colors being set properly.

**Current behavior**
The borders are white no matter what color I use for $cell-border-color.

**Expected behavior**
I expect the color value to appear as the cell borders.

**Screenshots or gifs**
<img width="671" alt="Screen Shot 2022-03-29 at 2 49 01 PM" src="https://user-images.githubusercontent.com/4992914/160712963-bafda668-861c-439d-95d5-e9b0ec22dab1.png">

**Your environment details**
 - Device:  desktop
 - OS: macOS
 - Browser chromium/electron

It looks like the styles are being set for the cell here without regard for CSS styles.  https://github.com/silevis/reactgrid/blob/develop/src/lib/Components/CellRenderer.tsx#L60

Because a `style` tag is used it overrides any upstream css values.

**Comment by joshuanathanson** [comment]
Bump, we need some help with this

**Comment by czerwiukk** [comment]
Hello!
Sorry for the delay, this issue is scheduled for our next sprint.
Thank you for reporting the issue!

**Comment by c3-anoopdixith** [comment]
Hi @czerwiukk  Any update on this? Could you let me know if this was fixed (and released)?

**Comment by czerwiukk** [comment]
Hello @c3-anoopdixith, we've released new version 4.0.4, the issue is resolved.
