### ISSUE TITLE
[question] Is there a way to test functionalities using react testing library or enzyme?

### ISSUE THREAD

**Issue by Castle33** [silevis/reactgrid#85]
I couldn't find in the docs any reference to testing. Is there a way to create tests to validate functionalities inside the reactgrid component? (for example, using react testing library or enzyme)

**Comment by g-e-n-v** [comment]
I have the same issue.

**Comment by Matt-Jensen** [comment]
Didn't have much luck testing anything beyond render output using testing-library.  However looks like they do have a lot of helpful [Cypress testing utils here](https://github.com/silevis/reactgrid/blob/develop/cypress/integration/common/utils.ts).

**Comment by DLowHP** [comment]
Just as @Matt-Jensen currently used test suite is Cypress, although we plan to update and/or rewrite tests so stay tuned :) (We'll most likely still use Cypress, but we might support other libraries as you suggested there).
I'm going to close this issue, but feel free to contact us if you need anything more, take care!
