### ISSUE TITLE
Merging cell feature

### ISSUE THREAD

**Issue by VikInnoTech** [silevis/reactgrid#88]
Hi guys!
Firstly, I'd like to say Thank you for your library.
Secondly, could you share your plans about implementing rest features for merging/unmerging cells?

**Comment by czerwiukk** [comment]
Hello!
Thank you for using ReactGrid and coming up with this feature.
Currently we're working on the next version of the library and this feature is on our roadmap.
Feel free to contribute if you feel like implementing it on the current codebase.

**Comment by seleckis** [comment]
Hi there, any update regarding the next version of the library?

**Comment by DLowHP** [comment]
Hi @seleckis! I've started working on the upcoming 5th version. Currently it's more of a back-and-forth experimenting so I don't commit so often, but you can still follow the changes on the [v5-dev](https://github.com/silevis/reactgrid/tree/v5-dev) branch. Feedback and help welcome! 😄

**Comment by LvChengbin** [comment]
@DLowHP Thank you for your great job and may I ask what's your plan of releasing version 5? I'm looking for a library for my project and merging cells is really an important feature that I need.

**Comment by DLowHP** [comment]
Hi! If you take a look at the v5-dev branch there's still a lot of work to do but I suppose we should be able to release the first v5 iteration in the Q1 2024. Keep your fingers crossed 🤞🏻 😁

**Comment by MichaelMatejko** [comment]
part of v5
