### ISSUE TITLE
Virtualization?

### ISSUE THREAD

**Issue by dregre** [silevis/reactgrid#91]
Hi folks,
Apologies — I couldn’t find this information in the docs.  Does ReactGrid support virtualization?  For example if I have a very large data set can I confidently pass it to ReactGrid so that it will gracefully reuse components and render only what is in or near the viewport?
Great work all around, this is by far the best UX I have found yet!  (Your sticky headers don’t lag — that’s amazing!)
best,
DreGre

**Comment by czerwiukk** [comment]
Hello!
Virtual scrolling is enabled by default.
There's also an option to disable it by using `disableVirtualScrolling` prop.
