### ISSUE TITLE
Got an error when I edit a cell

### ISSUE THREAD

**Issue by ChristoRibeiro** [silevis/reactgrid#92]
**Describe the bug**
I'm trying to edit a cell but I get an Error: `cannot read properties of undefined (reading 'scrollableElement')`

**Current behavior**
I get an error every time I change the content of a cell.

**Expected behavior**
The cell should get a new value without error.

**Screenshots or gifs**
![CleanShot 2022-05-31 at 18 02 59](https://user-images.githubusercontent.com/743358/171218716-68ea0b71-db38-4750-aeb1-e037c0665faf.gif)

**Your environment details**
 - Device:  desktop
 - OS: macOS
 - Browser chrome

**Comment by ChristoRibeiro** [comment]
Any idea @patryk0493?

Here is a github repo to test: https://github.com/ChristoRibeiro/reactgrid-test

**Comment by czerwiukk** [comment]
Hello, thank you for reporting the issue and also providing the reproduction repo.
I'll investigate this bug asap.

**Comment by czerwiukk** [comment]
Hi! @ChristoRibeiro!
Turns out that React's strict mode breaks our internal logic. We're going to investigate it, but for now please treat disabling it as a temporary solution.
You can disable it in the nuxt config.
```
// next.config.js
module.exports = {
  reactStrictMode: false,
}
```
Thank you for your patience!

**Comment by czerwiukk** [comment]
We're currently building the next version of ReactGrid from the ground up and decided to leave this topic in the current state. If you want to use the current version, disable the strict mode while using React 18.
