### ISSUE TITLE
How to use react-grid for react version 18

### ISSUE THREAD

**Issue by sharunspi** [silevis/reactgrid#98]
**Issue**
I am working with react v 18 and i would like to use react-grid library. If i need to shift to other react versions i need to downgrade some libraries also . Is there any fix for this

**Environment details**
 - OS: Ubuntu
 - Browser : Chromium

**Comment by czerwiukk** [comment]
We're aware that using strict mode in React 18 breaks our component. While we investigate it, please disable strict mode as a temporary solution.

**Comment by czerwiukk** [comment]
We're currently building the next version of ReactGrid from the ground up and decided to leave this topic in the current state. If you want to use the current version, disable the strict mode while using React 18.
